//! Field-level encryption at rest for the user's own typed content --
//! `reflection.text`, `daily_task_list.content`, and `not_to_do_list.content`
//! (see CLAUDE.md's "Encryption at rest" for the scope and threat model),
//! plus `reflection.created_at`/`updated_at`: those carry no prose, but a
//! plaintext edit timestamp leaks when the user is awake and working, which
//! is exactly the kind of inference the rest of this module exists to
//! prevent.
//!
//! **Why not SQLCipher / whole-database encryption**: tauri-plugin-sql (v2.4.0,
//! read from its own source) opens its pool with a bare `Pool::connect(url)` --
//! there is no hook to issue the `PRAGMA key` SQLCipher requires immediately
//! after connecting, and no way to pass custom connect options. Whole-db
//! encryption would mean forking or vendoring the plugin. Field encryption
//! needs none of that, and costs nothing in query capability here: no code
//! path in this app filters, searches, or sorts on the *value* of any
//! encrypted column (every `WHERE` is on `id`/`slot_start_at`/`date`/`rev`),
//! so an opaque ciphertext blob breaks no query.
//!
//! `created_at`/`updated_at` used to be in that list of things queries run
//! on -- P2P sync compared them to find changed rows. Encrypting them meant
//! that cursor had to move off timestamps entirely, which is what
//! `reflection.rev` and the other synced tables' `rev` columns are for
//! (db.rs migration 28, p2p_sync.rs's `build_delta_payload`).
//!
//! **Format**: `enc1:` + base64(`nonce` ‖ `ciphertext` ‖ `tag`), stored in the
//! same existing `TEXT` column -- no schema change. The `enc1:` marker is
//! load-bearing in two directions: `decrypt` returns anything *without* it
//! untouched (so a not-yet-migrated plaintext row is still readable rather
//! than an error), and the migration below skips anything *with* it (so it
//! can be re-run any number of times without double-encrypting).
//!
//! **Nonces are always freshly random, never derived from another column.**
//! That is not a stylistic choice: `updateReflectionText`,
//! `bulkUpsertReflections`, and import.rs's merge-then-`UPDATE` all rewrite
//! `text` for the *same* `id`/`slot_start_at`, so a nonce derived from either
//! would repeat across genuinely different plaintexts under one key -- the
//! failure mode that leaks the XOR of both plaintexts and, for GCM, the
//! authentication key itself. XChaCha20-Poly1305's 192-bit nonce is what
//! makes "just generate a random one every time" safe at any volume without
//! a counter shared between this module's several independent callers
//! (commands.rs for db.ts, import.rs, native_overlay.rs on Android).

use std::time::Duration;

// Desktop only: on Android the cipher work happens inside the Keystore via
// the Kotlin bridge, so none of the primitives below are compiled in.
#[cfg(not(target_os = "android"))]
use base64::engine::general_purpose::STANDARD as BASE64;
#[cfg(not(target_os = "android"))]
use base64::Engine as _;
#[cfg(not(target_os = "android"))]
use chacha20poly1305::aead::{Aead, AeadCore, KeyInit, OsRng};
#[cfg(not(target_os = "android"))]
use chacha20poly1305::XChaCha20Poly1305;
#[cfg(not(target_os = "android"))]
use hkdf::Hkdf;
#[cfg(not(target_os = "android"))]
use hmac::{Hmac, Mac};
use sqlx::{Row, Sqlite, Transaction};
#[cfg(not(target_os = "android"))]
use sha2::Sha256;
use tauri::AppHandle;
#[cfg(not(target_os = "android"))]
use tokio::sync::OnceCell;

use crate::db;

/// Marks a stored value as ciphertext this module produced. Anything without
/// it is treated as legacy plaintext and passed through untouched.
const MARKER: &str = "enc1:";

/// XChaCha20-Poly1305's nonce width. The whole reason this cipher was picked
/// over AES-256-GCM's 96 bits -- see the module doc comment. (Android's
/// Keystore path uses AES-GCM with its own 12-byte IV instead, generated by
/// the platform -- see NativeBridgePlugin.kt.)
#[cfg(not(target_os = "android"))]
const NONCE_LEN: usize = 24;

#[cfg(not(target_os = "android"))]
const KEY_LEN: usize = 32;

/// HKDF `info` label for the HMAC subkey that backs
/// `screen_time_session.app_id_hash` (see `FieldCipher::blind_index_many`).
/// Never the raw AEAD key itself -- reusing one raw key for two different
/// cryptographic primitives (AEAD encryption and a MAC) is a key-separation
/// anti-pattern this label exists to avoid. Android has no equivalent
/// derivation: its Keystore key is non-exportable, so it uses a second,
/// independently generated Keystore HMAC key instead (see
/// android_bridge.rs's `hmac_fields` / `NativeBridgePlugin.kt`'s
/// `HMAC_KEY_ALIAS`) rather than deriving anything from the AEAD key.
#[cfg(not(target_os = "android"))]
const BLIND_INDEX_HKDF_INFO: &[u8] = b"reflectodoro/screen_time/app_id_hash/v1";

/// Identifies this app's entry in the OS credential store. Deliberately the
/// same bundle identifier used for `app_config_dir()`/`app_log_dir()`.
#[cfg(not(target_os = "android"))]
const KEYRING_SERVICE: &str = "com.reflectodoro.app";
#[cfg(not(target_os = "android"))]
const KEYRING_ENTRY: &str = "db-encryption-key";

/// Filename of the fallback key, alongside `pomodoro.db` in
/// `app_config_dir()`. Only written when the OS credential store is
/// unavailable or demonstrably not persisting (see `load_or_create_key`).
#[cfg(not(target_os = "android"))]
const KEY_FILE: &str = "encryption.key";

// --- Cipher handle ---------------------------------------------------------

/// Resolved once per operation (or once per import/sync batch) and reused for
/// every field in it, rather than re-fetching the key per row: on Linux that
/// fetch is a D-Bus round trip, and on Android every call is a JNI hop into
/// the Keystore.
///
/// The platform split lives inside this one type so every caller
/// (commands.rs, import.rs, p2p_sync.rs, native_overlay.rs) is written once
/// against the same API: on desktop it carries the raw key and does the
/// crypto here in Rust; on Android it carries the `AppHandle` and delegates
/// to the Keystore through the Kotlin bridge, because an Android Keystore key
/// is non-exportable by design -- Rust never sees key material there.
#[derive(Clone)]
pub struct FieldCipher {
    #[cfg(not(target_os = "android"))]
    key: [u8; KEY_LEN],
    #[cfg(target_os = "android")]
    app: AppHandle,
}

impl FieldCipher {
    #[cfg(not(target_os = "android"))]
    pub async fn resolve(app: &AppHandle) -> Result<Self, String> {
        Ok(Self { key: *key(app).await? })
    }

    #[cfg(target_os = "android")]
    pub async fn resolve(app: &AppHandle) -> Result<Self, String> {
        Ok(Self { app: app.clone() })
    }

    /// Encrypts one value. Always produces a fresh nonce, so calling this
    /// twice on identical input yields two unrelated ciphertexts.
    pub async fn encrypt(&self, plaintext: &str) -> Result<String, String> {
        Ok(self.encrypt_many(std::slice::from_ref(&plaintext.to_string())).await?.remove(0))
    }

    /// Returns `stored` unchanged when it carries no `enc1:` marker -- a row
    /// the migration hasn't reached yet, or one written by a build from
    /// before this feature existed. Deliberately not an error: those rows are
    /// genuinely plaintext and genuinely readable, and failing here would
    /// make the app unusable for the window between first launch of this
    /// version and the migration completing.
    pub async fn decrypt(&self, stored: &str) -> Result<String, String> {
        if !stored.starts_with(MARKER) {
            return Ok(stored.to_string());
        }
        Ok(self.decrypt_many(std::slice::from_ref(&stored.to_string())).await?.remove(0))
    }

    #[cfg(not(target_os = "android"))]
    pub async fn encrypt_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        values.iter().map(|v| encrypt_with_key(&self.key, v)).collect()
    }

    #[cfg(not(target_os = "android"))]
    pub async fn decrypt_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        values.iter().map(|v| decrypt_with_key(&self.key, v)).collect()
    }

    /// One bridge call for the whole batch rather than one per value -- every
    /// call here is a JNI hop plus a Keystore `Cipher` init.
    #[cfg(target_os = "android")]
    pub async fn encrypt_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        crate::android_bridge::encrypt_fields(&self.app, values)
    }

    #[cfg(target_os = "android")]
    pub async fn decrypt_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        // Unmarked values never reach Kotlin: they're legacy plaintext and
        // would fail base64/AEAD decoding there. Same passthrough rule as
        // `decrypt`, applied per element so a mixed batch (part migrated,
        // part not) still works.
        let marked: Vec<String> = values.iter().filter(|v| v.starts_with(MARKER)).cloned().collect();
        if marked.is_empty() {
            return Ok(values.to_vec());
        }
        let mut decrypted = crate::android_bridge::decrypt_fields(&self.app, &marked)?.into_iter();
        values
            .iter()
            .map(|v| {
                if v.starts_with(MARKER) {
                    decrypted.next().ok_or_else(|| "android bridge returned too few values".to_string())
                } else {
                    Ok(v.clone())
                }
            })
            .collect()
    }

    /// Deterministic "blind index" for `screen_time_session.app_id` (see
    /// CLAUDE.md's "Encryption at rest"): the same input always produces the
    /// same output under one device's key, which is what lets
    /// `getScreenTimeForDate`'s `GROUP BY` and `import.rs`'s duplicate check
    /// keep working in SQL once `app_id` itself is random-nonce ciphertext
    /// (and therefore never equal to itself across two encryptions). Never
    /// used to recover the plaintext -- HMAC isn't reversible -- only to
    /// tell "these two rows are the same app" apart from "different apps".
    #[cfg(not(target_os = "android"))]
    pub async fn blind_index_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        let hk = Hkdf::<Sha256>::new(None, &self.key);
        let mut subkey = [0u8; 32];
        hk.expand(BLIND_INDEX_HKDF_INFO, &mut subkey).map_err(|e| format!("HKDF expand failed: {e}"))?;
        values
            .iter()
            .map(|v| {
                // Fully qualified: `KeyInit` (already in scope for the AEAD
                // cipher above) and `hmac::Mac` both define
                // `new_from_slice`, which is ambiguous without this.
                let mut mac = <Hmac<Sha256> as Mac>::new_from_slice(&subkey)
                    .map_err(|e| format!("HMAC init failed: {e}"))?;
                mac.update(v.as_bytes());
                Ok(BASE64.encode(mac.finalize().into_bytes()))
            })
            .collect()
    }

    /// Android has no raw key to derive from (see `BLIND_INDEX_HKDF_INFO`'s
    /// doc comment), so this runs against a second, independently generated
    /// Keystore HMAC key instead, entirely inside Kotlin.
    #[cfg(target_os = "android")]
    pub async fn blind_index_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        crate::android_bridge::hmac_fields(&self.app, values)
    }

    /// Fixed-key cipher for tests (import.rs's DB-backed tests in
    /// particular), which have no `AppHandle` and must not touch the real
    /// OS credential store.
    #[cfg(test)]
    pub fn test_fixed() -> Self {
        Self { key: [7u8; KEY_LEN] }
    }
}

// --- Cipher primitives (desktop) -------------------------------------------

#[cfg(not(target_os = "android"))]
fn encrypt_with_key(key: &[u8; KEY_LEN], plaintext: &str) -> Result<String, String> {
    let cipher = XChaCha20Poly1305::new(key.into());
    let nonce = XChaCha20Poly1305::generate_nonce(&mut OsRng);
    let ciphertext = cipher
        .encrypt(&nonce, plaintext.as_bytes())
        .map_err(|e| format!("encryption failed: {e}"))?;
    let mut blob = Vec::with_capacity(NONCE_LEN + ciphertext.len());
    blob.extend_from_slice(&nonce);
    blob.extend_from_slice(&ciphertext);
    Ok(format!("{MARKER}{}", BASE64.encode(blob)))
}

#[cfg(not(target_os = "android"))]
fn decrypt_with_key(key: &[u8; KEY_LEN], stored: &str) -> Result<String, String> {
    let Some(encoded) = stored.strip_prefix(MARKER) else {
        return Ok(stored.to_string());
    };
    let blob = BASE64.decode(encoded).map_err(|e| format!("ciphertext is not valid base64: {e}"))?;
    if blob.len() <= NONCE_LEN {
        return Err("ciphertext is too short to contain a nonce".to_string());
    }
    let (nonce, ciphertext) = blob.split_at(NONCE_LEN);
    let cipher = XChaCha20Poly1305::new(key.into());
    // A failure here is authentication failing, which in practice means the
    // wrong key -- most plausibly a credential store that lost or rotated
    // this app's entry. Surfaced as an error rather than silently swallowed:
    // pretending a row is empty would look exactly like "the user wrote
    // nothing", and the Entries page would quietly render a blank day.
    let plaintext = cipher
        .decrypt(nonce.into(), ciphertext)
        .map_err(|_| "decryption failed (wrong key, or the stored value was modified)".to_string())?;
    String::from_utf8(plaintext).map_err(|e| format!("decrypted value is not valid UTF-8: {e}"))
}

// --- Key material (desktop) ------------------------------------------------

#[cfg(not(target_os = "android"))]
static KEY: OnceCell<[u8; KEY_LEN]> = OnceCell::const_new();

/// Cached for the process lifetime: on Linux this is a D-Bus round trip to
/// the Secret Service, which has no business running on every reflection
/// save. Same `OnceCell` shape `native_overlay::pool` already uses.
#[cfg(not(target_os = "android"))]
async fn key(app: &AppHandle) -> Result<&'static [u8; KEY_LEN], String> {
    KEY.get_or_try_init(|| async {
        let app = app.clone();
        // keyring's access is synchronous and can block (D-Bus, Keychain),
        // so it stays off the async runtime's worker threads.
        tauri::async_runtime::spawn_blocking(move || load_or_create_key(&app))
            .await
            .map_err(|e| format!("key load task failed: {e}"))?
    })
    .await
}

/// Order matters here. The OS store is checked first so an existing key is
/// always found where it was put; the key file is checked *second* rather
/// than being a last resort only, so a device that already fell back once
/// keeps using the same key on every later launch instead of oscillating
/// between the two stores (which would leave half the rows unreadable).
#[cfg(not(target_os = "android"))]
fn load_or_create_key(app: &AppHandle) -> Result<[u8; KEY_LEN], String> {
    match keyring_get() {
        Ok(Some(key)) => return Ok(key),
        Ok(None) => {}
        Err(e) => log::warn!("crypto: OS credential store unreadable ({e}); trying the key file"),
    }

    if let Some(key) = file_get(app)? {
        return Ok(key);
    }

    let key = random_key();
    // Verified, not assumed: keyring built without a real backend silently
    // substitutes an in-memory store, and a key that evaporates on exit
    // would mean a fresh key every launch and every already-encrypted row
    // becoming permanently unreadable. A store that can't hand the value
    // back immediately is treated as no store at all.
    match keyring_set_verified(&key) {
        Ok(()) => {
            log::info!("crypto: generated a new at-rest key and stored it in the OS credential store");
            Ok(key)
        }
        Err(e) => {
            log::warn!(
                "crypto: OS credential store did not persist the key ({e}); \
                 falling back to a key file in the app config dir"
            );
            file_put(app, &key)?;
            Ok(key)
        }
    }
}

#[cfg(not(target_os = "android"))]
fn random_key() -> [u8; KEY_LEN] {
    use chacha20poly1305::aead::rand_core::RngCore;
    let mut key = [0u8; KEY_LEN];
    OsRng.fill_bytes(&mut key);
    key
}

#[cfg(not(target_os = "android"))]
fn keyring_entry() -> Result<keyring::Entry, String> {
    keyring::Entry::new(KEYRING_SERVICE, KEYRING_ENTRY).map_err(|e| e.to_string())
}

/// `Ok(None)` means "no entry yet" (a first run), which is not an error --
/// distinct from `Err`, which means the store itself couldn't be reached.
#[cfg(not(target_os = "android"))]
fn keyring_get() -> Result<Option<[u8; KEY_LEN]>, String> {
    match keyring_entry()?.get_password() {
        Ok(encoded) => decode_key(&encoded).map(Some),
        Err(keyring::Error::NoEntry) => Ok(None),
        Err(e) => Err(e.to_string()),
    }
}

#[cfg(not(target_os = "android"))]
fn keyring_set_verified(key: &[u8; KEY_LEN]) -> Result<(), String> {
    keyring_entry()?.set_password(&BASE64.encode(key)).map_err(|e| e.to_string())?;
    // Deliberately a fresh Entry, not the one just written through: reading
    // back via the same handle could be satisfied by an in-process cache and
    // would prove nothing about persistence.
    match keyring_get()? {
        Some(stored) if stored == *key => Ok(()),
        Some(_) => Err("credential store returned a different key than was just written".to_string()),
        None => Err("credential store reported no entry immediately after writing one".to_string()),
    }
}

#[cfg(not(target_os = "android"))]
fn key_file_path(app: &AppHandle) -> Result<std::path::PathBuf, String> {
    use tauri::Manager;
    let dir = app.path().app_config_dir().map_err(|e| format!("no app config dir: {e}"))?;
    std::fs::create_dir_all(&dir).map_err(|e| format!("couldn't create app config dir: {e}"))?;
    Ok(dir.join(KEY_FILE))
}

#[cfg(not(target_os = "android"))]
fn file_get(app: &AppHandle) -> Result<Option<[u8; KEY_LEN]>, String> {
    let path = key_file_path(app)?;
    match std::fs::read_to_string(&path) {
        Ok(encoded) => decode_key(encoded.trim()).map(Some),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(format!("couldn't read key file: {e}")),
    }
}

#[cfg(not(target_os = "android"))]
fn file_put(app: &AppHandle, key: &[u8; KEY_LEN]) -> Result<(), String> {
    let path = key_file_path(app)?;
    std::fs::write(&path, BASE64.encode(key)).map_err(|e| format!("couldn't write key file: {e}"))?;
    // Windows already restricts %APPDATA% to the owning user by default ACL;
    // Unix umasks vary enough to be worth setting explicitly.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600))
            .map_err(|e| format!("couldn't restrict key file permissions: {e}"))?;
    }
    Ok(())
}

#[cfg(not(target_os = "android"))]
fn decode_key(encoded: &str) -> Result<[u8; KEY_LEN], String> {
    let bytes = BASE64.decode(encoded).map_err(|e| format!("stored key is not valid base64: {e}"))?;
    bytes.try_into().map_err(|_| "stored key is not the expected length".to_string())
}

// --- One-time migration of existing plaintext rows -------------------------

/// `app_setting` key recording that every pre-existing row has been
/// encrypted. Not the only guard -- the per-row `enc1:` check is what
/// actually makes this idempotent -- but it keeps a fully migrated database
/// from re-scanning every row on every launch.
const MIGRATED_KEY: &str = "data_encryption_migrated";

/// The encrypted columns, as (table, primary key column, value column). The
/// three user-typed-text columns store prose; `wellness_check`'s four
/// boolean columns each store the plain string `"1"`/`"0"` instead --
/// `getWellnessSummaryForDate` used to aggregate these in SQL (`SUM`/`COUNT`),
/// which is why they were excluded for a while, but that aggregation now
/// happens app-side (decrypt-then-sum) instead -- see CLAUDE.md.
/// wellness_check's columns are `TEXT` (migration 23) specifically so they
/// can round-trip through this same generic string-based helper.
/// `reflection`'s two timestamp columns are here so a *fresh* install
/// encrypts them on its first pass. An install that already set
/// `MIGRATED_KEY` before they were added skips this list entirely, which is
/// why they also get their own backfill under
/// `REFLECTION_TIMESTAMP_MIGRATED_KEY` below.
const ENCRYPTED_COLUMNS: [(&str, &str, &str); 9] = [
    ("reflection", "id", "text"),
    ("reflection", "id", "created_at"),
    ("reflection", "id", "updated_at"),
    ("daily_task_list", "date", "content"),
    ("not_to_do_list", "date", "content"),
    ("wellness_check", "id", "relaxed_eyes"),
    ("wellness_check", "id", "exercise"),
    ("wellness_check", "id", "drank_water"),
    ("wellness_check", "id", "washroom"),
];

/// Spawned from `lib.rs`'s `setup()`. Runs the original four-table migration,
/// the `screen_time_session` one (see `SCREEN_TIME_MIGRATED_KEY`), and the
/// `reflection` timestamp one (see `REFLECTION_TIMESTAMP_MIGRATED_KEY`) as
/// independently retried passes, each with its own flag: an install that
/// already has `MIGRATED_KEY = "true"` from before app names or timestamps
/// were encrypted would otherwise skip those later backfills entirely if they
/// all shared one flag.
pub async fn run_encryption_migration_after_db_ready(app: AppHandle) {
    retry_migration(app.clone(), "data", migrate_once).await;
    retry_migration(app.clone(), "screen_time_session", migrate_screen_time_sessions_once).await;
    retry_migration(app, "reflection timestamps", migrate_reflection_timestamps_once).await;
}

/// Retries on the same cold-start race
/// `p2p_sync::get_or_create_device_id_after_db_ready` exists for: `.setup()`
/// runs before the frontend's `Database.load()` has necessarily created
/// `pomodoro.db` or applied its migrations, so the first few attempts here
/// can legitimately fail with "no such table".
///
/// Giving up after the last attempt is safe, not a data hazard: new writes
/// are encrypted regardless of whether this ran, and rows it hasn't reached
/// stay readable through `decrypt`'s passthrough. The next launch tries
/// again.
///
/// Takes `app` by value (cloned per attempt below) rather than by
/// reference: an `async fn(&AppHandle) -> impl Future` function item's
/// implicit borrow doesn't satisfy a plain `F: FnMut(&AppHandle) -> Fut`
/// bound (the required higher-ranked lifetime isn't expressible with a
/// single fixed `Fut` type), and `AppHandle` is a cheap `Clone` handle
/// anyway.
async fn retry_migration<F, Fut>(app: AppHandle, label: &str, mut attempt: F)
where
    F: FnMut(AppHandle) -> Fut,
    Fut: std::future::Future<Output = Result<Option<usize>, String>>,
{
    const MAX_ATTEMPTS: u32 = 10;
    const RETRY_DELAY: Duration = Duration::from_millis(750);

    let mut last_err = String::new();
    for _ in 0..MAX_ATTEMPTS {
        match attempt(app.clone()).await {
            Ok(Some(count)) => {
                log::info!("crypto: {label} encryption-at-rest migration complete, {count} row(s) encrypted");
                return;
            }
            Ok(None) => return, // already migrated
            Err(e) => {
                last_err = e;
                tokio::time::sleep(RETRY_DELAY).await;
            }
        }
    }
    log::error!(
        "crypto: {label} encryption-at-rest migration did not run this session ({last_err}); \
         existing rows stay readable as plaintext and it will be retried on next launch"
    );
}

/// `Ok(None)` = already migrated, nothing to do.
async fn migrate_once(app: AppHandle) -> Result<Option<usize>, String> {
    let pool = db::open_direct_pool(&app).await?;

    let done: Option<String> = sqlx::query_scalar("SELECT value FROM app_setting WHERE key = ?")
        .bind(MIGRATED_KEY)
        .fetch_optional(&pool)
        .await
        .map_err(|e| e.to_string())?;
    if done.as_deref() == Some("true") {
        return Ok(None);
    }

    let cipher = FieldCipher::resolve(&app).await?;
    let mut tx = pool.begin().await.map_err(|e| format!("failed to start migration transaction: {e}"))?;

    let mut encrypted = 0usize;
    for (table, key_column, value_column) in ENCRYPTED_COLUMNS {
        encrypted += encrypt_existing_rows(&mut tx, &cipher, table, key_column, value_column).await?;
    }

    sqlx::query(
        "INSERT INTO app_setting (key, value) VALUES (?, 'true')
         ON CONFLICT(key) DO UPDATE SET value = excluded.value",
    )
    .bind(MIGRATED_KEY)
    .execute(&mut *tx)
    .await
    .map_err(|e| e.to_string())?;

    tx.commit().await.map_err(|e| format!("failed to commit migration transaction: {e}"))?;
    Ok(Some(encrypted))
}

/// Deliberately does not touch `updated_at` on any row it rewrites: that
/// column is P2P sync's delta cursor (see CLAUDE.md's "Delta cursor"), and
/// re-encrypting a row is a storage-format change, not a content edit --
/// bumping it would make every paired device re-send its entire history on
/// the next sync for no reason.
///
/// `table`/`key_column`/`value_column` come only from `ENCRYPTED_COLUMNS`
/// above, never from user input, so interpolating them into the SQL is safe
/// here -- sqlx cannot bind an identifier as a parameter. Same reasoning
/// import.rs's `merge_import_day_rows` already documents.
async fn encrypt_existing_rows(
    tx: &mut Transaction<'_, Sqlite>,
    cipher: &FieldCipher,
    table: &str,
    key_column: &str,
    value_column: &str,
) -> Result<usize, String> {
    let rows = sqlx::query(&format!("SELECT {key_column}, {value_column} FROM {table}"))
        .fetch_all(&mut **tx)
        .await
        .map_err(|e| format!("couldn't read {table} for encryption: {e}"))?;

    let mut pending: Vec<(String, String)> = Vec::new();
    for row in &rows {
        // reflection's key is INTEGER and the two day-list tables' is TEXT;
        // reading both as a string keeps one code path for all three.
        let key: String = row
            .try_get::<String, _>(key_column)
            .or_else(|_| row.try_get::<i64, _>(key_column).map(|n| n.to_string()))
            .map_err(|e| format!("couldn't read {table}.{key_column}: {e}"))?;
        // `reflection.updated_at` is nullable (migration 19 backfilled it but
        // never made it NOT NULL), so read it as an Option and leave NULL
        // alone -- encrypting it would turn "never edited" into a value.
        let value: Option<String> =
            row.try_get(value_column).map_err(|e| format!("couldn't read {table}.{value_column}: {e}"))?;
        let Some(value) = value else { continue };
        if !value.starts_with(MARKER) {
            pending.push((key, value));
        }
    }
    if pending.is_empty() {
        return Ok(0);
    }

    let plaintexts: Vec<String> = pending.iter().map(|(_, v)| v.clone()).collect();
    let ciphertexts = cipher.encrypt_many(&plaintexts).await?;

    for ((key, _), ciphertext) in pending.iter().zip(ciphertexts) {
        sqlx::query(&format!("UPDATE {table} SET {value_column} = ? WHERE {key_column} = ?"))
            .bind(&ciphertext)
            .bind(key)
            .execute(&mut **tx)
            .await
            .map_err(|e| format!("couldn't encrypt a {table} row: {e}"))?;
    }
    Ok(pending.len())
}

/// `app_setting` key for the one-time backfill of `screen_time_session`'s
/// `app_id`/`display_name` (encryption) and `app_id_hash` (blind index).
/// Deliberately separate from `MIGRATED_KEY`: an install that already ran
/// the original four-table migration has `MIGRATED_KEY = "true"` and would
/// otherwise skip this table's backfill entirely if both shared one flag --
/// see CLAUDE.md's "Encryption at rest".
const SCREEN_TIME_MIGRATED_KEY: &str = "screen_time_encryption_migrated";

/// Rows per backfill batch. `screen_time_session` is documented (CLAUDE.md)
/// as likely to become the largest table by row count, and on Android every
/// batch is at least two JNI bridge round trips (decrypt, blind-index,
/// encrypt) -- chunking keeps any one pass bounded instead of pulling an
/// entire history into memory and one giant transaction.
const SCREEN_TIME_MIGRATION_CHUNK: i64 = 500;

/// Not built on the generic `ENCRYPTED_COLUMNS`/`encrypt_existing_rows`
/// machinery above: that helper only ever rewrites one ciphertext column
/// for a row it already knows the key of, with no way to also compute and
/// write a derived `app_id_hash` alongside it. `Ok(None)` = already
/// migrated, nothing to do.
///
/// Every row this touches is selected by `WHERE app_id_hash = ''`, so a row
/// already handled by a previous run (or one written after this feature
/// shipped, which always sets `app_id_hash` at insert/import time -- see
/// db.ts's `saveScreenTimeSessions` and `import.rs`) is never revisited.
/// Each batch commits in its own transaction, so a crash mid-backfill
/// leaves already-committed batches fully encrypted+hashed and the rest
/// untouched plaintext -- never a row with ciphertext but no hash, which is
/// what makes re-running this safe.
async fn migrate_screen_time_sessions_once(app: AppHandle) -> Result<Option<usize>, String> {
    let pool = db::open_direct_pool(&app).await?;

    let done: Option<String> = sqlx::query_scalar("SELECT value FROM app_setting WHERE key = ?")
        .bind(SCREEN_TIME_MIGRATED_KEY)
        .fetch_optional(&pool)
        .await
        .map_err(|e| e.to_string())?;
    if done.as_deref() == Some("true") {
        return Ok(None);
    }

    let cipher = FieldCipher::resolve(&app).await?;
    let total = encrypt_and_hash_screen_time_rows(&pool, &cipher).await?;

    sqlx::query(
        "INSERT INTO app_setting (key, value) VALUES (?, 'true')
         ON CONFLICT(key) DO UPDATE SET value = excluded.value",
    )
    .bind(SCREEN_TIME_MIGRATED_KEY)
    .execute(&pool)
    .await
    .map_err(|e| e.to_string())?;

    Ok(Some(total))
}

/// The testable core of the screen-time backfill -- takes a pool and cipher
/// directly (no `AppHandle`) so tests can drive it against an in-memory
/// database with `FieldCipher::test_fixed()`, the same split
/// `encrypt_existing_rows`/`migrate_once` already have. Returns how many
/// rows were encrypted+hashed.
async fn encrypt_and_hash_screen_time_rows(pool: &sqlx::SqlitePool, cipher: &FieldCipher) -> Result<usize, String> {
    let mut total = 0usize;

    loop {
        let rows = sqlx::query("SELECT id, app_id, display_name FROM screen_time_session WHERE app_id_hash = '' LIMIT ?")
            .bind(SCREEN_TIME_MIGRATION_CHUNK)
            .fetch_all(pool)
            .await
            .map_err(|e| format!("couldn't read screen_time_session for encryption: {e}"))?;
        if rows.is_empty() {
            break;
        }

        let ids: Vec<i64> = rows
            .iter()
            .map(|r| r.try_get("id"))
            .collect::<Result<_, _>>()
            .map_err(|e| format!("couldn't read screen_time_session.id: {e}"))?;
        let raw_app_ids: Vec<String> = rows
            .iter()
            .map(|r| r.try_get("app_id"))
            .collect::<Result<_, _>>()
            .map_err(|e| format!("couldn't read screen_time_session.app_id: {e}"))?;
        let raw_display_names: Vec<String> = rows
            .iter()
            .map(|r| r.try_get("display_name"))
            .collect::<Result<_, _>>()
            .map_err(|e| format!("couldn't read screen_time_session.display_name: {e}"))?;

        // `decrypt_many` passes plaintext through untouched, so this is
        // correct whichever state these rows are actually in.
        let plaintext_app_ids = cipher.decrypt_many(&raw_app_ids).await?;
        let hashes = cipher.blind_index_many(&plaintext_app_ids).await?;
        let encrypted_app_ids = cipher.encrypt_many(&plaintext_app_ids).await?;

        // Empty `display_name` stays plain `''` -- same rule the write path
        // uses (readers already treat `""` as "no friendly name", and
        // encrypting nothing would only cost a decrypt on every later read
        // for no benefit).
        let plaintext_display_names = cipher.decrypt_many(&raw_display_names).await?;
        let to_encrypt: Vec<String> = plaintext_display_names.iter().filter(|v| !v.is_empty()).cloned().collect();
        let mut encrypted_non_empty =
            if to_encrypt.is_empty() { Vec::new() } else { cipher.encrypt_many(&to_encrypt).await? }.into_iter();
        let mut encrypted_display_names = Vec::with_capacity(plaintext_display_names.len());
        for v in &plaintext_display_names {
            if v.is_empty() {
                encrypted_display_names.push(String::new());
            } else {
                encrypted_display_names
                    .push(encrypted_non_empty.next().ok_or("display_name encryption returned too few values")?);
            }
        }

        let mut tx =
            pool.begin().await.map_err(|e| format!("failed to start screen_time_session migration transaction: {e}"))?;
        for i in 0..rows.len() {
            sqlx::query("UPDATE screen_time_session SET app_id = ?, display_name = ?, app_id_hash = ? WHERE id = ?")
                .bind(&encrypted_app_ids[i])
                .bind(&encrypted_display_names[i])
                .bind(&hashes[i])
                .bind(ids[i])
                .execute(&mut *tx)
                .await
                .map_err(|e| format!("couldn't encrypt a screen_time_session row: {e}"))?;
        }
        tx.commit().await.map_err(|e| format!("failed to commit screen_time_session migration transaction: {e}"))?;

        total += rows.len();
    }

    Ok(total)
}

/// `app_setting` key for the one-time backfill of `reflection`'s
/// `created_at`/`updated_at`. Separate from `MIGRATED_KEY` for exactly the
/// reason `SCREEN_TIME_MIGRATED_KEY` is: any install that already ran the
/// original migration has `MIGRATED_KEY = "true"` and would skip these two
/// columns forever if they only lived in `ENCRYPTED_COLUMNS`.
const REFLECTION_TIMESTAMP_MIGRATED_KEY: &str = "reflection_timestamp_encryption_migrated";

/// Rows per backfill batch, same reasoning as `SCREEN_TIME_MIGRATION_CHUNK`
/// (bounded memory, and on Android each batch is a JNI round trip).
const REFLECTION_TIMESTAMP_MIGRATION_CHUNK: i64 = 500;

/// Unlike `encrypt_existing_rows`, this rewrites *two* columns per row in one
/// UPDATE rather than one column per pass -- `reflection` is the one table
/// where both of a row's timestamps move together, and doing them separately
/// would double the row rewrites (and so double the `rev` churn described
/// below). `Ok(None)` = already migrated, nothing to do.
///
/// **This one deliberately breaks the "never bump the sync cursor" rule that
/// `encrypt_existing_rows` documents**, because it cannot do otherwise:
/// migration 28's `AFTER UPDATE` trigger owns `reflection.rev` now, and its
/// `WHEN NEW.rev = OLD.rev` guard fires precisely when a writer leaves rev
/// alone -- so there is no way to rewrite a row without advancing it. The
/// consequence is bounded and one-time: on the first launch after upgrading,
/// a paired device re-sends its `reflection` history once. The merge logic is
/// idempotent (per-slot line merge, natural-key dedupe), so this costs LAN
/// bandwidth on one sync and nothing else. `screen_time_session`, the largest
/// table, is unaffected -- its own backfill flag is already set on any install
/// that reaches this one.
async fn migrate_reflection_timestamps_once(app: AppHandle) -> Result<Option<usize>, String> {
    let pool = db::open_direct_pool(&app).await?;

    let done: Option<String> = sqlx::query_scalar("SELECT value FROM app_setting WHERE key = ?")
        .bind(REFLECTION_TIMESTAMP_MIGRATED_KEY)
        .fetch_optional(&pool)
        .await
        .map_err(|e| e.to_string())?;
    if done.as_deref() == Some("true") {
        return Ok(None);
    }

    let cipher = FieldCipher::resolve(&app).await?;
    let total = encrypt_reflection_timestamp_rows(&pool, &cipher).await?;

    sqlx::query(
        "INSERT INTO app_setting (key, value) VALUES (?, 'true')
         ON CONFLICT(key) DO UPDATE SET value = excluded.value",
    )
    .bind(REFLECTION_TIMESTAMP_MIGRATED_KEY)
    .execute(&pool)
    .await
    .map_err(|e| e.to_string())?;

    Ok(Some(total))
}

/// Testable core of the timestamp backfill -- takes a pool and cipher
/// directly so tests can drive it with `FieldCipher::test_fixed()`, the same
/// split `encrypt_and_hash_screen_time_rows` has.
///
/// Selects on the `enc1:` marker rather than a sentinel column, so a row an
/// earlier run already handled is never revisited and the whole pass stays
/// re-runnable. Each batch commits in its own transaction: a crash
/// mid-backfill leaves committed rows fully encrypted and the rest readable
/// plaintext, never a half-encrypted row.
async fn encrypt_reflection_timestamp_rows(pool: &sqlx::SqlitePool, cipher: &FieldCipher) -> Result<usize, String> {
    let mut total = 0usize;

    loop {
        let rows = sqlx::query(
            "SELECT id, created_at, updated_at FROM reflection
             WHERE created_at NOT LIKE 'enc1:%'
                OR (updated_at IS NOT NULL AND updated_at NOT LIKE 'enc1:%')
             LIMIT ?",
        )
        .bind(REFLECTION_TIMESTAMP_MIGRATION_CHUNK)
        .fetch_all(pool)
        .await
        .map_err(|e| format!("couldn't read reflection for timestamp encryption: {e}"))?;
        if rows.is_empty() {
            break;
        }

        let ids: Vec<i64> = rows
            .iter()
            .map(|r| r.try_get("id"))
            .collect::<Result<_, _>>()
            .map_err(|e| format!("couldn't read reflection.id: {e}"))?;
        let created: Vec<String> = rows
            .iter()
            .map(|r| r.try_get("created_at"))
            .collect::<Result<_, _>>()
            .map_err(|e| format!("couldn't read reflection.created_at: {e}"))?;
        let updated: Vec<Option<String>> = rows
            .iter()
            .map(|r| r.try_get("updated_at"))
            .collect::<Result<_, _>>()
            .map_err(|e| format!("couldn't read reflection.updated_at: {e}"))?;

        // One batch per column rather than per row: on Android each call is a
        // JNI hop into the Keystore. `encrypt` is only applied to values that
        // aren't already ciphertext, so a partially-migrated row (created_at
        // done, updated_at not) can't get double-encrypted.
        let encrypted_created = encrypt_unmarked(cipher, &created).await?;
        let updated_present: Vec<String> = updated.iter().flatten().cloned().collect();
        let encrypted_present = encrypt_unmarked(cipher, &updated_present).await?;
        let mut encrypted_present = encrypted_present.into_iter();

        let mut tx =
            pool.begin().await.map_err(|e| format!("failed to start reflection timestamp transaction: {e}"))?;
        for i in 0..rows.len() {
            let new_updated = match &updated[i] {
                Some(_) => Some(encrypted_present.next().ok_or("updated_at encryption returned too few values")?),
                None => None,
            };
            sqlx::query("UPDATE reflection SET created_at = ?, updated_at = ? WHERE id = ?")
                .bind(&encrypted_created[i])
                .bind(&new_updated)
                .bind(ids[i])
                .execute(&mut *tx)
                .await
                .map_err(|e| format!("couldn't encrypt a reflection row's timestamps: {e}"))?;
        }
        tx.commit().await.map_err(|e| format!("failed to commit reflection timestamp transaction: {e}"))?;

        total += rows.len();
    }

    Ok(total)
}

/// Encrypts only the values that aren't already `enc1:`-marked, preserving
/// order, in a single batched call.
async fn encrypt_unmarked(cipher: &FieldCipher, values: &[String]) -> Result<Vec<String>, String> {
    let plain: Vec<String> = values.iter().filter(|v| !v.starts_with(MARKER)).cloned().collect();
    if plain.is_empty() {
        return Ok(values.to_vec());
    }
    let mut encrypted = cipher.encrypt_many(&plain).await?.into_iter();

    let mut out = Vec::with_capacity(values.len());
    for value in values {
        if value.starts_with(MARKER) {
            out.push(value.clone());
        } else {
            out.push(encrypted.next().ok_or("encryption returned too few values")?);
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn round_trips_a_value() {
        let cipher = FieldCipher::test_fixed();
        let encrypted = cipher.encrypt("Did yoga").await.unwrap();
        assert!(encrypted.starts_with(MARKER));
        assert!(!encrypted.contains("Did yoga"));
        assert_eq!(cipher.decrypt(&encrypted).await.unwrap(), "Did yoga");
    }

    /// The property the whole nonce discussion rests on: identical plaintext
    /// must not produce identical ciphertext, or an attacker could tell which
    /// slots share an entry (and, with any known plaintext, start unpicking
    /// the rest).
    #[tokio::test]
    async fn same_plaintext_encrypts_differently_every_time() {
        let cipher = FieldCipher::test_fixed();
        let a = cipher.encrypt("Skip").await.unwrap();
        let b = cipher.encrypt("Skip").await.unwrap();
        assert_ne!(a, b, "a fresh nonce must make repeat encryptions of one value unlinkable");
        assert_eq!(cipher.decrypt(&a).await.unwrap(), "Skip");
        assert_eq!(cipher.decrypt(&b).await.unwrap(), "Skip");
    }

    /// Legacy/not-yet-migrated rows must survive a decrypt call untouched --
    /// this is what keeps the app readable between first launch of this
    /// version and the migration finishing.
    #[tokio::test]
    async fn unmarked_plaintext_passes_through_untouched() {
        let cipher = FieldCipher::test_fixed();
        assert_eq!(cipher.decrypt("Went for a walk").await.unwrap(), "Went for a walk");
        assert_eq!(cipher.decrypt("").await.unwrap(), "");
    }

    #[tokio::test]
    async fn empty_and_multiline_values_round_trip() {
        let cipher = FieldCipher::test_fixed();
        for value in ["", "Line one\nLine two", "  leading and trailing  ", "emoji 🌱 and ünïcode"] {
            let encrypted = cipher.encrypt(value).await.unwrap();
            assert_eq!(cipher.decrypt(&encrypted).await.unwrap(), value);
        }
    }

    #[tokio::test]
    async fn a_different_key_cannot_decrypt() {
        let cipher = FieldCipher::test_fixed();
        let encrypted = cipher.encrypt("Did laundry").await.unwrap();
        let other = FieldCipher { key: [9u8; KEY_LEN] };
        assert!(other.decrypt(&encrypted).await.is_err(), "the wrong key must fail loudly, not return garbage");
    }

    #[tokio::test]
    async fn tampered_ciphertext_is_rejected() {
        let cipher = FieldCipher::test_fixed();
        let encrypted = cipher.encrypt("Reviewed the PR").await.unwrap();
        // Flip a character in the base64 body -- AEAD authentication is what
        // should catch this, not a silently wrong plaintext.
        let mut chars: Vec<char> = encrypted.chars().collect();
        let last = chars.len() - 2;
        chars[last] = if chars[last] == 'A' { 'B' } else { 'A' };
        let tampered: String = chars.into_iter().collect();
        assert!(cipher.decrypt(&tampered).await.is_err());
    }

    #[tokio::test]
    async fn batch_round_trips_and_preserves_order() {
        let cipher = FieldCipher::test_fixed();
        let values: Vec<String> = ["first", "second", "third"].iter().map(|s| s.to_string()).collect();
        let encrypted = cipher.encrypt_many(&values).await.unwrap();
        assert_eq!(cipher.decrypt_many(&encrypted).await.unwrap(), values);
    }

    // --- Blind index (screen_time_session.app_id_hash) ---------------------

    /// The property `getScreenTimeForDate`'s `GROUP BY` and `import.rs`'s
    /// duplicate check both rest on: the same plaintext under one key always
    /// produces the same hash, unlike `encrypt` (which never repeats).
    #[tokio::test]
    async fn blind_index_is_deterministic() {
        let cipher = FieldCipher::test_fixed();
        let a = cipher.blind_index_many(&["chrome.exe".to_string()]).await.unwrap();
        let b = cipher.blind_index_many(&["chrome.exe".to_string()]).await.unwrap();
        assert_eq!(a, b);
    }

    #[tokio::test]
    async fn blind_index_differs_for_different_values() {
        let cipher = FieldCipher::test_fixed();
        let hashes = cipher.blind_index_many(&["chrome.exe".to_string(), "notepad.exe".to_string()]).await.unwrap();
        assert_ne!(hashes[0], hashes[1]);
    }

    /// A device's hash values must not match another device's for the same
    /// app name -- this is what makes the "won't link across users" property
    /// hold without any coordination between devices.
    #[tokio::test]
    async fn blind_index_differs_across_keys() {
        let a = FieldCipher::test_fixed();
        let b = FieldCipher { key: [9u8; KEY_LEN] };
        let hash_a = a.blind_index_many(&["chrome.exe".to_string()]).await.unwrap();
        let hash_b = b.blind_index_many(&["chrome.exe".to_string()]).await.unwrap();
        assert_ne!(hash_a, hash_b);
    }

    /// Proves the HMAC subkey is actually derived via HKDF rather than the
    /// raw AEAD key being reused directly as the MAC key -- the key-
    /// separation property the whole `BLIND_INDEX_HKDF_INFO` label exists
    /// for.
    #[tokio::test]
    async fn blind_index_does_not_use_the_raw_aead_key_directly() {
        let cipher = FieldCipher::test_fixed();
        let hash = cipher.blind_index_many(&["chrome.exe".to_string()]).await.unwrap().remove(0);

        let mut raw_key_mac = <Hmac<Sha256> as Mac>::new_from_slice(&cipher.key).unwrap();
        raw_key_mac.update(b"chrome.exe");
        let raw_key_hash = BASE64.encode(raw_key_mac.finalize().into_bytes());

        assert_ne!(hash, raw_key_hash);
    }

    // --- Migration of pre-existing plaintext rows -------------------------

    async fn migration_test_pool() -> sqlx::SqlitePool {
        let pool = sqlx::SqlitePool::connect("sqlite::memory:").await.unwrap();
        sqlx::query(
            "CREATE TABLE reflection (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at TEXT NOT NULL,
                slot_start_at TEXT NOT NULL,
                text TEXT NOT NULL,
                updated_at TEXT
            )",
        )
        .execute(&pool)
        .await
        .unwrap();
        sqlx::query(
            "CREATE TABLE daily_task_list (
                date TEXT PRIMARY KEY,
                content TEXT NOT NULL DEFAULT '',
                updated_at TEXT NOT NULL
            )",
        )
        .execute(&pool)
        .await
        .unwrap();
        sqlx::query(
            // TEXT columns (migration 23), same as production -- see this
            // module's ENCRYPTED_COLUMNS.
            "CREATE TABLE wellness_check (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                slot_start_at TEXT NOT NULL DEFAULT '',
                relaxed_eyes TEXT NOT NULL DEFAULT '1',
                exercise TEXT NOT NULL DEFAULT '1',
                drank_water TEXT NOT NULL DEFAULT '1',
                washroom TEXT NOT NULL DEFAULT '0',
                created_at TEXT NOT NULL
            )",
        )
        .execute(&pool)
        .await
        .unwrap();
        sqlx::query(
            // Migration 24's shape: app_id_hash defaults to '' for
            // pre-existing rows, which is exactly what
            // encrypt_and_hash_screen_time_rows selects on.
            "CREATE TABLE screen_time_session (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                app_id TEXT NOT NULL,
                display_name TEXT NOT NULL DEFAULT '',
                app_id_hash TEXT NOT NULL DEFAULT '',
                platform TEXT NOT NULL,
                device_name TEXT NOT NULL,
                started_at TEXT NOT NULL,
                ended_at TEXT NOT NULL
            )",
        )
        .execute(&pool)
        .await
        .unwrap();
        pool
    }

    #[tokio::test]
    async fn migration_encrypts_existing_plaintext_rows() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        sqlx::query(
            "INSERT INTO reflection (id, created_at, slot_start_at, text, updated_at)
             VALUES (1, '2026-01-01T00:00:00.000Z', '2026-01-01T00:00:00.000Z', 'Did yoga', '2026-01-01T00:00:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();

        let mut tx = pool.begin().await.unwrap();
        let count = encrypt_existing_rows(&mut tx, &cipher, "reflection", "id", "text").await.unwrap();
        tx.commit().await.unwrap();
        assert_eq!(count, 1);

        let stored: String =
            sqlx::query_scalar("SELECT text FROM reflection WHERE id = 1").fetch_one(&pool).await.unwrap();
        assert!(stored.starts_with(MARKER), "row should be encrypted in place");
        assert_eq!(cipher.decrypt(&stored).await.unwrap(), "Did yoga", "content must survive the migration verbatim");
    }

    /// The property that makes a crash mid-migration (or a lost/reset
    /// `data_encryption_migrated` flag) harmless rather than destructive:
    /// running the pass again must not encrypt already-encrypted values a
    /// second time, which would leave them undecryptable in one pass.
    #[tokio::test]
    async fn migration_is_idempotent() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        sqlx::query(
            "INSERT INTO reflection (id, created_at, slot_start_at, text, updated_at)
             VALUES (1, '2026-01-01T00:00:00.000Z', '2026-01-01T00:00:00.000Z', 'Did yoga', '2026-01-01T00:00:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();

        for _ in 0..3 {
            let mut tx = pool.begin().await.unwrap();
            encrypt_existing_rows(&mut tx, &cipher, "reflection", "id", "text").await.unwrap();
            tx.commit().await.unwrap();
        }

        // A second pass must report nothing left to do, and one decrypt must
        // still yield the original text (not another layer of ciphertext).
        let mut tx = pool.begin().await.unwrap();
        let count = encrypt_existing_rows(&mut tx, &cipher, "reflection", "id", "text").await.unwrap();
        tx.commit().await.unwrap();
        assert_eq!(count, 0, "an already-encrypted row must not be re-encrypted");

        let stored: String =
            sqlx::query_scalar("SELECT text FROM reflection WHERE id = 1").fetch_one(&pool).await.unwrap();
        assert_eq!(cipher.decrypt(&stored).await.unwrap(), "Did yoga");
    }

    /// Re-encrypting is a storage-format change, not a content edit. Bumping
    /// updated_at would make every paired device re-sync its entire history
    /// on the next P2P sync (that column is the delta cursor -- see CLAUDE.md).
    #[tokio::test]
    async fn migration_leaves_the_sync_cursor_alone() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        sqlx::query(
            "INSERT INTO reflection (id, created_at, slot_start_at, text, updated_at)
             VALUES (1, '2026-01-01T00:00:00.000Z', '2026-01-01T00:00:00.000Z', 'Did yoga', '2026-01-01T09:30:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();
        sqlx::query(
            "INSERT INTO daily_task_list (date, content, updated_at)
             VALUES ('2026-01-01', 'Write report', '2026-01-01T08:00:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();

        let mut tx = pool.begin().await.unwrap();
        encrypt_existing_rows(&mut tx, &cipher, "reflection", "id", "text").await.unwrap();
        encrypt_existing_rows(&mut tx, &cipher, "daily_task_list", "date", "content").await.unwrap();
        tx.commit().await.unwrap();

        let reflection_updated: String =
            sqlx::query_scalar("SELECT updated_at FROM reflection WHERE id = 1").fetch_one(&pool).await.unwrap();
        assert_eq!(reflection_updated, "2026-01-01T09:30:00.000Z");
        let task_updated: String =
            sqlx::query_scalar("SELECT updated_at FROM daily_task_list WHERE date = '2026-01-01'")
                .fetch_one(&pool)
                .await
                .unwrap();
        assert_eq!(task_updated, "2026-01-01T08:00:00.000Z");
    }

    /// `reflection` is keyed by INTEGER and the day-list tables by TEXT --
    /// the migration reads both through one code path, so both need covering.
    #[tokio::test]
    async fn migration_handles_a_text_keyed_table() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        sqlx::query(
            "INSERT INTO daily_task_list (date, content, updated_at)
             VALUES ('2026-01-01', 'Write report\nCall dentist', '2026-01-01T08:00:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();

        let mut tx = pool.begin().await.unwrap();
        let count = encrypt_existing_rows(&mut tx, &cipher, "daily_task_list", "date", "content").await.unwrap();
        tx.commit().await.unwrap();
        assert_eq!(count, 1);

        let stored: String =
            sqlx::query_scalar("SELECT content FROM daily_task_list WHERE date = '2026-01-01'")
                .fetch_one(&pool)
                .await
                .unwrap();
        assert_eq!(cipher.decrypt(&stored).await.unwrap(), "Write report\nCall dentist");
    }

    /// `wellness_check` is the one table with four encrypted columns sharing
    /// a single `id`-keyed row (every other encrypted table has exactly one
    /// value column) -- confirms `ENCRYPTED_COLUMNS`' four separate
    /// (table, "id", column) entries each migrate their own column
    /// independently, without disturbing the other three.
    #[tokio::test]
    async fn migration_handles_wellness_checks_four_columns() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        sqlx::query(
            "INSERT INTO wellness_check (id, slot_start_at, relaxed_eyes, exercise, drank_water, washroom, created_at)
             VALUES (1, '2026-01-01T00:00:00.000Z', '1', '0', '1', '0', '2026-01-01T00:05:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();

        let mut tx = pool.begin().await.unwrap();
        for column in ["relaxed_eyes", "exercise", "drank_water", "washroom"] {
            encrypt_existing_rows(&mut tx, &cipher, "wellness_check", "id", column).await.unwrap();
        }
        tx.commit().await.unwrap();

        let row = sqlx::query("SELECT relaxed_eyes, exercise, drank_water, washroom FROM wellness_check WHERE id = 1")
            .fetch_one(&pool)
            .await
            .unwrap();
        let expected = [("relaxed_eyes", "1"), ("exercise", "0"), ("drank_water", "1"), ("washroom", "0")];
        for (column, plaintext) in expected {
            let stored: String = row.try_get(column).unwrap();
            assert!(stored.starts_with(MARKER), "{column} should have been stored encrypted, got: {stored}");
            assert_eq!(cipher.decrypt(&stored).await.unwrap(), plaintext, "{column} must survive the migration verbatim");
        }
    }

    /// A batch mixing already-migrated and not-yet-migrated rows is exactly
    /// what a partially migrated database hands `getReflectionsForDate`.
    #[tokio::test]
    async fn batch_decrypt_handles_a_mix_of_encrypted_and_plaintext() {
        let cipher = FieldCipher::test_fixed();
        let encrypted = cipher.encrypt("encrypted row").await.unwrap();
        let mixed = vec![encrypted, "legacy plaintext row".to_string()];
        assert_eq!(
            cipher.decrypt_many(&mixed).await.unwrap(),
            vec!["encrypted row".to_string(), "legacy plaintext row".to_string()]
        );
    }

    // --- screen_time_session backfill (app_id/display_name + app_id_hash) --

    #[tokio::test]
    async fn screen_time_backfill_encrypts_and_hashes_plaintext_rows() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        sqlx::query(
            "INSERT INTO screen_time_session (id, app_id, display_name, platform, device_name, started_at, ended_at)
             VALUES (1, 'chrome.exe', 'Google Chrome', 'windows', 'desktop', '2026-01-01T00:00:00.000Z', '2026-01-01T00:05:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();

        let count = encrypt_and_hash_screen_time_rows(&pool, &cipher).await.unwrap();
        assert_eq!(count, 1);

        let row = sqlx::query("SELECT app_id, display_name, app_id_hash, started_at FROM screen_time_session WHERE id = 1")
            .fetch_one(&pool)
            .await
            .unwrap();
        let app_id: String = row.try_get("app_id").unwrap();
        let display_name: String = row.try_get("display_name").unwrap();
        let app_id_hash: String = row.try_get("app_id_hash").unwrap();
        let started_at: String = row.try_get("started_at").unwrap();

        assert!(app_id.starts_with(MARKER));
        assert_eq!(cipher.decrypt(&app_id).await.unwrap(), "chrome.exe");
        assert!(display_name.starts_with(MARKER));
        assert_eq!(cipher.decrypt(&display_name).await.unwrap(), "Google Chrome");
        assert_eq!(app_id_hash, cipher.blind_index_many(&["chrome.exe".to_string()]).await.unwrap()[0]);
        assert_eq!(started_at, "2026-01-01T00:00:00.000Z", "the sync cursor column must be untouched");
    }

    /// Empty `display_name` (no friendly name resolved) must stay plain --
    /// same rule the write path uses, so `MAX(display_name)`-style logic
    /// still prefers a real label over ciphertext-of-nothing.
    #[tokio::test]
    async fn screen_time_backfill_leaves_empty_display_name_plain() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        sqlx::query(
            "INSERT INTO screen_time_session (id, app_id, display_name, platform, device_name, started_at, ended_at)
             VALUES (1, 'unknown.bin', '', 'windows', 'desktop', '2026-01-01T00:00:00.000Z', '2026-01-01T00:05:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();

        encrypt_and_hash_screen_time_rows(&pool, &cipher).await.unwrap();

        let display_name: String =
            sqlx::query_scalar("SELECT display_name FROM screen_time_session WHERE id = 1").fetch_one(&pool).await.unwrap();
        assert_eq!(display_name, "");
    }

    /// Two rows for the same app must hash identically -- the property
    /// `getScreenTimeForDate`'s `GROUP BY app_id_hash` depends on.
    #[tokio::test]
    async fn screen_time_backfill_hashes_identically_for_the_same_app() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        sqlx::query(
            "INSERT INTO screen_time_session (id, app_id, display_name, platform, device_name, started_at, ended_at)
             VALUES
                (1, 'chrome.exe', 'Google Chrome', 'windows', 'desktop', '2026-01-01T00:00:00.000Z', '2026-01-01T00:05:00.000Z'),
                (2, 'chrome.exe', 'Google Chrome', 'windows', 'desktop', '2026-01-01T00:10:00.000Z', '2026-01-01T00:20:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();

        encrypt_and_hash_screen_time_rows(&pool, &cipher).await.unwrap();

        let hashes: Vec<String> =
            sqlx::query_scalar("SELECT app_id_hash FROM screen_time_session ORDER BY id").fetch_all(&pool).await.unwrap();
        assert_eq!(hashes[0], hashes[1]);
        // But the ciphertext itself must still differ (fresh nonce each
        // time) -- the hash is the only thing that's allowed to repeat.
        let app_ids: Vec<String> =
            sqlx::query_scalar("SELECT app_id FROM screen_time_session ORDER BY id").fetch_all(&pool).await.unwrap();
        assert_ne!(app_ids[0], app_ids[1]);
    }

    /// Running the backfill again must be a no-op: every row it already
    /// touched has a non-empty `app_id_hash`, so the `WHERE app_id_hash = ''`
    /// selection finds nothing left to do.
    #[tokio::test]
    async fn screen_time_backfill_is_idempotent() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        sqlx::query(
            "INSERT INTO screen_time_session (id, app_id, display_name, platform, device_name, started_at, ended_at)
             VALUES (1, 'chrome.exe', 'Google Chrome', 'windows', 'desktop', '2026-01-01T00:00:00.000Z', '2026-01-01T00:05:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();

        assert_eq!(encrypt_and_hash_screen_time_rows(&pool, &cipher).await.unwrap(), 1);
        assert_eq!(encrypt_and_hash_screen_time_rows(&pool, &cipher).await.unwrap(), 0, "already-hashed rows must not be re-touched");

        let app_id: String = sqlx::query_scalar("SELECT app_id FROM screen_time_session WHERE id = 1").fetch_one(&pool).await.unwrap();
        assert_eq!(cipher.decrypt(&app_id).await.unwrap(), "chrome.exe", "content must survive verbatim");
    }

    // --- reflection.created_at / updated_at backfill ----------------------

    async fn seed_reflection(pool: &sqlx::SqlitePool, id: i64, created: &str, updated: Option<&str>) {
        sqlx::query("INSERT INTO reflection (id, created_at, slot_start_at, text, updated_at) VALUES (?, ?, 'slot', 'text', ?)")
            .bind(id)
            .bind(created)
            .bind(updated)
            .execute(pool)
            .await
            .unwrap();
    }

    #[tokio::test]
    async fn reflection_timestamp_backfill_encrypts_both_columns() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        seed_reflection(&pool, 1, "2026-01-01T09:00:00.000Z", Some("2026-01-01T09:30:00.000Z")).await;

        assert_eq!(encrypt_reflection_timestamp_rows(&pool, &cipher).await.unwrap(), 1);

        let row = sqlx::query("SELECT created_at, updated_at FROM reflection WHERE id = 1").fetch_one(&pool).await.unwrap();
        let created: String = row.get("created_at");
        let updated: String = row.get("updated_at");
        assert!(created.starts_with(MARKER), "created_at should be ciphertext");
        assert!(updated.starts_with(MARKER), "updated_at should be ciphertext");
        assert_eq!(cipher.decrypt(&created).await.unwrap(), "2026-01-01T09:00:00.000Z");
        assert_eq!(cipher.decrypt(&updated).await.unwrap(), "2026-01-01T09:30:00.000Z");
    }

    /// A NULL `updated_at` means "never edited since insert" -- encrypting it
    /// would turn the absence of a value into a value, and `COALESCE`-style
    /// readers would stop seeing it as absent.
    #[tokio::test]
    async fn reflection_timestamp_backfill_leaves_null_updated_at_null() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        seed_reflection(&pool, 1, "2026-01-01T09:00:00.000Z", None).await;

        assert_eq!(encrypt_reflection_timestamp_rows(&pool, &cipher).await.unwrap(), 1);

        let updated: Option<String> =
            sqlx::query_scalar("SELECT updated_at FROM reflection WHERE id = 1").fetch_one(&pool).await.unwrap();
        assert_eq!(updated, None, "a NULL updated_at must stay NULL");
    }

    /// The `enc1:` marker, not a sentinel column, is what makes this
    /// re-runnable -- a crash between chunks must not double-encrypt.
    #[tokio::test]
    async fn reflection_timestamp_backfill_is_idempotent() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        seed_reflection(&pool, 1, "2026-01-01T09:00:00.000Z", Some("2026-01-01T09:30:00.000Z")).await;

        assert_eq!(encrypt_reflection_timestamp_rows(&pool, &cipher).await.unwrap(), 1);
        assert_eq!(encrypt_reflection_timestamp_rows(&pool, &cipher).await.unwrap(), 0, "already-encrypted rows must not be re-touched");

        let created: String =
            sqlx::query_scalar("SELECT created_at FROM reflection WHERE id = 1").fetch_one(&pool).await.unwrap();
        assert_eq!(cipher.decrypt(&created).await.unwrap(), "2026-01-01T09:00:00.000Z", "content must survive verbatim");
    }

    /// A row half-done by an interrupted earlier run (created_at encrypted,
    /// updated_at not) has to be finished without re-encrypting the part
    /// that's already ciphertext.
    #[tokio::test]
    async fn reflection_timestamp_backfill_finishes_a_partial_row() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        let already = cipher.encrypt("2026-01-01T09:00:00.000Z").await.unwrap();
        seed_reflection(&pool, 1, &already, Some("2026-01-01T09:30:00.000Z")).await;

        assert_eq!(encrypt_reflection_timestamp_rows(&pool, &cipher).await.unwrap(), 1);

        let row = sqlx::query("SELECT created_at, updated_at FROM reflection WHERE id = 1").fetch_one(&pool).await.unwrap();
        let created: String = row.get("created_at");
        let updated: String = row.get("updated_at");
        assert_eq!(created, already, "an already-encrypted value must be left byte-for-byte alone");
        assert_eq!(cipher.decrypt(&updated).await.unwrap(), "2026-01-01T09:30:00.000Z");
    }

    /// The whole reason this backfill exists separately from `migrate_once`:
    /// every existing install already has `data_encryption_migrated = 'true'`,
    /// so folding these columns into `ENCRYPTED_COLUMNS` alone would silently
    /// never encrypt them on any real device.
    #[tokio::test]
    async fn reflection_timestamp_backfill_is_not_gated_on_the_original_flag() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        sqlx::query("CREATE TABLE app_setting (key TEXT PRIMARY KEY, value TEXT NOT NULL)").execute(&pool).await.unwrap();
        sqlx::query("INSERT INTO app_setting (key, value) VALUES (?, 'true')")
            .bind(MIGRATED_KEY)
            .execute(&pool)
            .await
            .unwrap();
        seed_reflection(&pool, 1, "2026-01-01T09:00:00.000Z", Some("2026-01-01T09:30:00.000Z")).await;

        // migrate_once would bail here; this pass must not.
        assert_eq!(encrypt_reflection_timestamp_rows(&pool, &cipher).await.unwrap(), 1);
        assert_ne!(
            REFLECTION_TIMESTAMP_MIGRATED_KEY, MIGRATED_KEY,
            "the two passes must not share a flag or the second never runs"
        );
    }

    /// More rows than one chunk, to confirm the loop actually drains rather
    /// than stopping after the first batch.
    #[tokio::test]
    async fn reflection_timestamp_backfill_drains_past_one_chunk() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        let total = REFLECTION_TIMESTAMP_MIGRATION_CHUNK + 7;
        for id in 1..=total {
            seed_reflection(&pool, id, "2026-01-01T09:00:00.000Z", Some("2026-01-01T09:30:00.000Z")).await;
        }

        assert_eq!(encrypt_reflection_timestamp_rows(&pool, &cipher).await.unwrap(), total as usize);

        let remaining: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM reflection WHERE created_at NOT LIKE 'enc1:%'")
            .fetch_one(&pool)
            .await
            .unwrap();
        assert_eq!(remaining, 0, "every row should be encrypted after one pass");
    }
}
