//! Field-level encryption at rest for the user's own typed content --
//! `reflection.text`, `daily_task_list.content`, and `not_to_do_list.content`
//! (see CLAUDE.md's "Encryption at rest" for the scope and threat model).
//!
//! **Why not SQLCipher / whole-database encryption**: tauri-plugin-sql (v2.4.0,
//! read from its own source) opens its pool with a bare `Pool::connect(url)` --
//! there is no hook to issue the `PRAGMA key` SQLCipher requires immediately
//! after connecting, and no way to pass custom connect options. Whole-db
//! encryption would mean forking or vendoring the plugin. Field encryption
//! needs none of that, and costs nothing in query capability here: no code
//! path in this app filters, searches, or sorts on the *value* of any of
//! those three columns (every `WHERE` is on `id`/`slot_start_at`/`date`/
//! `created_at`/`updated_at`), so an opaque ciphertext blob breaks no query.
//!
//! **Format**: `enc1:` + base64(`nonce` ‖ `ciphertext` ‖ `tag`), stored in the
//! same existing `TEXT` column -- no schema change. The `enc1:` marker is
//! load-bearing in two directions: `decrypt` returns anything *without* it
//! untouched (so a not-yet-migrated plaintext row is still readable rather
//! than an error), and the migration below skips anything *with* it (so it
//! can be re-run any number of times without double-encrypting).
//!
//! **Nonces are always freshly random, never derived from another column.**
//! That is not a stylistic choice: `updateReflectionText`,
//! `bulkUpsertReflections`, and import.rs's merge-then-`UPDATE` all rewrite
//! `text` for the *same* `id`/`slot_start_at`, so a nonce derived from either
//! would repeat across genuinely different plaintexts under one key -- the
//! failure mode that leaks the XOR of both plaintexts and, for GCM, the
//! authentication key itself. XChaCha20-Poly1305's 192-bit nonce is what
//! makes "just generate a random one every time" safe at any volume without
//! a counter shared between this module's several independent callers
//! (commands.rs for db.ts, import.rs, native_overlay.rs on Android).

use std::time::Duration;

// Desktop only: on Android the cipher work happens inside the Keystore via
// the Kotlin bridge, so none of the primitives below are compiled in.
#[cfg(not(target_os = "android"))]
use base64::engine::general_purpose::STANDARD as BASE64;
#[cfg(not(target_os = "android"))]
use base64::Engine as _;
#[cfg(not(target_os = "android"))]
use chacha20poly1305::aead::{Aead, AeadCore, KeyInit, OsRng};
#[cfg(not(target_os = "android"))]
use chacha20poly1305::XChaCha20Poly1305;
use sqlx::{Row, Sqlite, Transaction};
use tauri::AppHandle;
#[cfg(not(target_os = "android"))]
use tokio::sync::OnceCell;

use crate::db;

/// Marks a stored value as ciphertext this module produced. Anything without
/// it is treated as legacy plaintext and passed through untouched.
const MARKER: &str = "enc1:";

/// XChaCha20-Poly1305's nonce width. The whole reason this cipher was picked
/// over AES-256-GCM's 96 bits -- see the module doc comment. (Android's
/// Keystore path uses AES-GCM with its own 12-byte IV instead, generated by
/// the platform -- see NativeBridgePlugin.kt.)
#[cfg(not(target_os = "android"))]
const NONCE_LEN: usize = 24;

#[cfg(not(target_os = "android"))]
const KEY_LEN: usize = 32;

/// Identifies this app's entry in the OS credential store. Deliberately the
/// same bundle identifier used for `app_config_dir()`/`app_log_dir()`.
#[cfg(not(target_os = "android"))]
const KEYRING_SERVICE: &str = "com.reflectodoro.app";
#[cfg(not(target_os = "android"))]
const KEYRING_ENTRY: &str = "db-encryption-key";

/// Filename of the fallback key, alongside `pomodoro.db` in
/// `app_config_dir()`. Only written when the OS credential store is
/// unavailable or demonstrably not persisting (see `load_or_create_key`).
#[cfg(not(target_os = "android"))]
const KEY_FILE: &str = "encryption.key";

// --- Cipher handle ---------------------------------------------------------

/// Resolved once per operation (or once per import/sync batch) and reused for
/// every field in it, rather than re-fetching the key per row: on Linux that
/// fetch is a D-Bus round trip, and on Android every call is a JNI hop into
/// the Keystore.
///
/// The platform split lives inside this one type so every caller
/// (commands.rs, import.rs, p2p_sync.rs, native_overlay.rs) is written once
/// against the same API: on desktop it carries the raw key and does the
/// crypto here in Rust; on Android it carries the `AppHandle` and delegates
/// to the Keystore through the Kotlin bridge, because an Android Keystore key
/// is non-exportable by design -- Rust never sees key material there.
#[derive(Clone)]
pub struct FieldCipher {
    #[cfg(not(target_os = "android"))]
    key: [u8; KEY_LEN],
    #[cfg(target_os = "android")]
    app: AppHandle,
}

impl FieldCipher {
    #[cfg(not(target_os = "android"))]
    pub async fn resolve(app: &AppHandle) -> Result<Self, String> {
        Ok(Self { key: *key(app).await? })
    }

    #[cfg(target_os = "android")]
    pub async fn resolve(app: &AppHandle) -> Result<Self, String> {
        Ok(Self { app: app.clone() })
    }

    /// Encrypts one value. Always produces a fresh nonce, so calling this
    /// twice on identical input yields two unrelated ciphertexts.
    pub async fn encrypt(&self, plaintext: &str) -> Result<String, String> {
        Ok(self.encrypt_many(std::slice::from_ref(&plaintext.to_string())).await?.remove(0))
    }

    /// Returns `stored` unchanged when it carries no `enc1:` marker -- a row
    /// the migration hasn't reached yet, or one written by a build from
    /// before this feature existed. Deliberately not an error: those rows are
    /// genuinely plaintext and genuinely readable, and failing here would
    /// make the app unusable for the window between first launch of this
    /// version and the migration completing.
    pub async fn decrypt(&self, stored: &str) -> Result<String, String> {
        if !stored.starts_with(MARKER) {
            return Ok(stored.to_string());
        }
        Ok(self.decrypt_many(std::slice::from_ref(&stored.to_string())).await?.remove(0))
    }

    #[cfg(not(target_os = "android"))]
    pub async fn encrypt_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        values.iter().map(|v| encrypt_with_key(&self.key, v)).collect()
    }

    #[cfg(not(target_os = "android"))]
    pub async fn decrypt_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        values.iter().map(|v| decrypt_with_key(&self.key, v)).collect()
    }

    /// One bridge call for the whole batch rather than one per value -- every
    /// call here is a JNI hop plus a Keystore `Cipher` init.
    #[cfg(target_os = "android")]
    pub async fn encrypt_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        crate::android_bridge::encrypt_fields(&self.app, values)
    }

    #[cfg(target_os = "android")]
    pub async fn decrypt_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        // Unmarked values never reach Kotlin: they're legacy plaintext and
        // would fail base64/AEAD decoding there. Same passthrough rule as
        // `decrypt`, applied per element so a mixed batch (part migrated,
        // part not) still works.
        let marked: Vec<String> = values.iter().filter(|v| v.starts_with(MARKER)).cloned().collect();
        if marked.is_empty() {
            return Ok(values.to_vec());
        }
        let mut decrypted = crate::android_bridge::decrypt_fields(&self.app, &marked)?.into_iter();
        values
            .iter()
            .map(|v| {
                if v.starts_with(MARKER) {
                    decrypted.next().ok_or_else(|| "android bridge returned too few values".to_string())
                } else {
                    Ok(v.clone())
                }
            })
            .collect()
    }

    /// Fixed-key cipher for tests (import.rs's DB-backed tests in
    /// particular), which have no `AppHandle` and must not touch the real
    /// OS credential store.
    #[cfg(test)]
    pub fn test_fixed() -> Self {
        Self { key: [7u8; KEY_LEN] }
    }
}

// --- Cipher primitives (desktop) -------------------------------------------

#[cfg(not(target_os = "android"))]
fn encrypt_with_key(key: &[u8; KEY_LEN], plaintext: &str) -> Result<String, String> {
    let cipher = XChaCha20Poly1305::new(key.into());
    let nonce = XChaCha20Poly1305::generate_nonce(&mut OsRng);
    let ciphertext = cipher
        .encrypt(&nonce, plaintext.as_bytes())
        .map_err(|e| format!("encryption failed: {e}"))?;
    let mut blob = Vec::with_capacity(NONCE_LEN + ciphertext.len());
    blob.extend_from_slice(&nonce);
    blob.extend_from_slice(&ciphertext);
    Ok(format!("{MARKER}{}", BASE64.encode(blob)))
}

#[cfg(not(target_os = "android"))]
fn decrypt_with_key(key: &[u8; KEY_LEN], stored: &str) -> Result<String, String> {
    let Some(encoded) = stored.strip_prefix(MARKER) else {
        return Ok(stored.to_string());
    };
    let blob = BASE64.decode(encoded).map_err(|e| format!("ciphertext is not valid base64: {e}"))?;
    if blob.len() <= NONCE_LEN {
        return Err("ciphertext is too short to contain a nonce".to_string());
    }
    let (nonce, ciphertext) = blob.split_at(NONCE_LEN);
    let cipher = XChaCha20Poly1305::new(key.into());
    // A failure here is authentication failing, which in practice means the
    // wrong key -- most plausibly a credential store that lost or rotated
    // this app's entry. Surfaced as an error rather than silently swallowed:
    // pretending a row is empty would look exactly like "the user wrote
    // nothing", and the Entries page would quietly render a blank day.
    let plaintext = cipher
        .decrypt(nonce.into(), ciphertext)
        .map_err(|_| "decryption failed (wrong key, or the stored value was modified)".to_string())?;
    String::from_utf8(plaintext).map_err(|e| format!("decrypted value is not valid UTF-8: {e}"))
}

// --- Key material (desktop) ------------------------------------------------

#[cfg(not(target_os = "android"))]
static KEY: OnceCell<[u8; KEY_LEN]> = OnceCell::const_new();

/// Cached for the process lifetime: on Linux this is a D-Bus round trip to
/// the Secret Service, which has no business running on every reflection
/// save. Same `OnceCell` shape `native_overlay::pool` already uses.
#[cfg(not(target_os = "android"))]
async fn key(app: &AppHandle) -> Result<&'static [u8; KEY_LEN], String> {
    KEY.get_or_try_init(|| async {
        let app = app.clone();
        // keyring's access is synchronous and can block (D-Bus, Keychain),
        // so it stays off the async runtime's worker threads.
        tauri::async_runtime::spawn_blocking(move || load_or_create_key(&app))
            .await
            .map_err(|e| format!("key load task failed: {e}"))?
    })
    .await
}

/// Order matters here. The OS store is checked first so an existing key is
/// always found where it was put; the key file is checked *second* rather
/// than being a last resort only, so a device that already fell back once
/// keeps using the same key on every later launch instead of oscillating
/// between the two stores (which would leave half the rows unreadable).
#[cfg(not(target_os = "android"))]
fn load_or_create_key(app: &AppHandle) -> Result<[u8; KEY_LEN], String> {
    match keyring_get() {
        Ok(Some(key)) => return Ok(key),
        Ok(None) => {}
        Err(e) => log::warn!("crypto: OS credential store unreadable ({e}); trying the key file"),
    }

    if let Some(key) = file_get(app)? {
        return Ok(key);
    }

    let key = random_key();
    // Verified, not assumed: keyring built without a real backend silently
    // substitutes an in-memory store, and a key that evaporates on exit
    // would mean a fresh key every launch and every already-encrypted row
    // becoming permanently unreadable. A store that can't hand the value
    // back immediately is treated as no store at all.
    match keyring_set_verified(&key) {
        Ok(()) => {
            log::info!("crypto: generated a new at-rest key and stored it in the OS credential store");
            Ok(key)
        }
        Err(e) => {
            log::warn!(
                "crypto: OS credential store did not persist the key ({e}); \
                 falling back to a key file in the app config dir"
            );
            file_put(app, &key)?;
            Ok(key)
        }
    }
}

#[cfg(not(target_os = "android"))]
fn random_key() -> [u8; KEY_LEN] {
    use chacha20poly1305::aead::rand_core::RngCore;
    let mut key = [0u8; KEY_LEN];
    OsRng.fill_bytes(&mut key);
    key
}

#[cfg(not(target_os = "android"))]
fn keyring_entry() -> Result<keyring::Entry, String> {
    keyring::Entry::new(KEYRING_SERVICE, KEYRING_ENTRY).map_err(|e| e.to_string())
}

/// `Ok(None)` means "no entry yet" (a first run), which is not an error --
/// distinct from `Err`, which means the store itself couldn't be reached.
#[cfg(not(target_os = "android"))]
fn keyring_get() -> Result<Option<[u8; KEY_LEN]>, String> {
    match keyring_entry()?.get_password() {
        Ok(encoded) => decode_key(&encoded).map(Some),
        Err(keyring::Error::NoEntry) => Ok(None),
        Err(e) => Err(e.to_string()),
    }
}

#[cfg(not(target_os = "android"))]
fn keyring_set_verified(key: &[u8; KEY_LEN]) -> Result<(), String> {
    keyring_entry()?.set_password(&BASE64.encode(key)).map_err(|e| e.to_string())?;
    // Deliberately a fresh Entry, not the one just written through: reading
    // back via the same handle could be satisfied by an in-process cache and
    // would prove nothing about persistence.
    match keyring_get()? {
        Some(stored) if stored == *key => Ok(()),
        Some(_) => Err("credential store returned a different key than was just written".to_string()),
        None => Err("credential store reported no entry immediately after writing one".to_string()),
    }
}

#[cfg(not(target_os = "android"))]
fn key_file_path(app: &AppHandle) -> Result<std::path::PathBuf, String> {
    use tauri::Manager;
    let dir = app.path().app_config_dir().map_err(|e| format!("no app config dir: {e}"))?;
    std::fs::create_dir_all(&dir).map_err(|e| format!("couldn't create app config dir: {e}"))?;
    Ok(dir.join(KEY_FILE))
}

#[cfg(not(target_os = "android"))]
fn file_get(app: &AppHandle) -> Result<Option<[u8; KEY_LEN]>, String> {
    let path = key_file_path(app)?;
    match std::fs::read_to_string(&path) {
        Ok(encoded) => decode_key(encoded.trim()).map(Some),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(format!("couldn't read key file: {e}")),
    }
}

#[cfg(not(target_os = "android"))]
fn file_put(app: &AppHandle, key: &[u8; KEY_LEN]) -> Result<(), String> {
    let path = key_file_path(app)?;
    std::fs::write(&path, BASE64.encode(key)).map_err(|e| format!("couldn't write key file: {e}"))?;
    // Windows already restricts %APPDATA% to the owning user by default ACL;
    // Unix umasks vary enough to be worth setting explicitly.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600))
            .map_err(|e| format!("couldn't restrict key file permissions: {e}"))?;
    }
    Ok(())
}

#[cfg(not(target_os = "android"))]
fn decode_key(encoded: &str) -> Result<[u8; KEY_LEN], String> {
    let bytes = BASE64.decode(encoded).map_err(|e| format!("stored key is not valid base64: {e}"))?;
    bytes.try_into().map_err(|_| "stored key is not the expected length".to_string())
}

// --- One-time migration of existing plaintext rows -------------------------

/// `app_setting` key recording that every pre-existing row has been
/// encrypted. Not the only guard -- the per-row `enc1:` check is what
/// actually makes this idempotent -- but it keeps a fully migrated database
/// from re-scanning every row on every launch.
const MIGRATED_KEY: &str = "data_encryption_migrated";

/// The encrypted columns, as (table, primary key column, value column). The
/// three user-typed-text columns store prose; `wellness_check`'s four
/// boolean columns each store the plain string `"1"`/`"0"` instead --
/// `getWellnessSummaryForDate` used to aggregate these in SQL (`SUM`/`COUNT`),
/// which is why they were excluded for a while, but that aggregation now
/// happens app-side (decrypt-then-sum) instead -- see CLAUDE.md.
/// wellness_check's columns are `TEXT` (migration 23) specifically so they
/// can round-trip through this same generic string-based helper.
const ENCRYPTED_COLUMNS: [(&str, &str, &str); 7] = [
    ("reflection", "id", "text"),
    ("daily_task_list", "date", "content"),
    ("not_to_do_list", "date", "content"),
    ("wellness_check", "id", "relaxed_eyes"),
    ("wellness_check", "id", "exercise"),
    ("wellness_check", "id", "drank_water"),
    ("wellness_check", "id", "washroom"),
];

/// Spawned from `lib.rs`'s `setup()`. Retries on the same cold-start race
/// `p2p_sync::get_or_create_device_id_after_db_ready` exists for: `.setup()`
/// runs before the frontend's `Database.load()` has necessarily created
/// `pomodoro.db` or applied its migrations, so the first few attempts here
/// can legitimately fail with "no such table".
///
/// Giving up after the last attempt is safe, not a data hazard: new writes
/// are encrypted regardless of whether this ran, and rows it hasn't reached
/// stay readable through `decrypt`'s passthrough. The next launch tries
/// again.
pub async fn run_encryption_migration_after_db_ready(app: AppHandle) {
    const MAX_ATTEMPTS: u32 = 10;
    const RETRY_DELAY: Duration = Duration::from_millis(750);

    let mut last_err = String::new();
    for _ in 0..MAX_ATTEMPTS {
        match migrate_once(&app).await {
            Ok(Some(count)) => {
                log::info!("crypto: encryption-at-rest migration complete, {count} row(s) encrypted");
                return;
            }
            Ok(None) => return, // already migrated
            Err(e) => {
                last_err = e;
                tokio::time::sleep(RETRY_DELAY).await;
            }
        }
    }
    log::error!(
        "crypto: encryption-at-rest migration did not run this session ({last_err}); \
         existing rows stay readable as plaintext and it will be retried on next launch"
    );
}

/// `Ok(None)` = already migrated, nothing to do.
async fn migrate_once(app: &AppHandle) -> Result<Option<usize>, String> {
    let pool = db::open_direct_pool(app).await?;

    let done: Option<String> = sqlx::query_scalar("SELECT value FROM app_setting WHERE key = ?")
        .bind(MIGRATED_KEY)
        .fetch_optional(&pool)
        .await
        .map_err(|e| e.to_string())?;
    if done.as_deref() == Some("true") {
        return Ok(None);
    }

    let cipher = FieldCipher::resolve(app).await?;
    let mut tx = pool.begin().await.map_err(|e| format!("failed to start migration transaction: {e}"))?;

    let mut encrypted = 0usize;
    for (table, key_column, value_column) in ENCRYPTED_COLUMNS {
        encrypted += encrypt_existing_rows(&mut tx, &cipher, table, key_column, value_column).await?;
    }

    sqlx::query(
        "INSERT INTO app_setting (key, value) VALUES (?, 'true')
         ON CONFLICT(key) DO UPDATE SET value = excluded.value",
    )
    .bind(MIGRATED_KEY)
    .execute(&mut *tx)
    .await
    .map_err(|e| e.to_string())?;

    tx.commit().await.map_err(|e| format!("failed to commit migration transaction: {e}"))?;
    Ok(Some(encrypted))
}

/// Deliberately does not touch `updated_at` on any row it rewrites: that
/// column is P2P sync's delta cursor (see CLAUDE.md's "Delta cursor"), and
/// re-encrypting a row is a storage-format change, not a content edit --
/// bumping it would make every paired device re-send its entire history on
/// the next sync for no reason.
///
/// `table`/`key_column`/`value_column` come only from `ENCRYPTED_COLUMNS`
/// above, never from user input, so interpolating them into the SQL is safe
/// here -- sqlx cannot bind an identifier as a parameter. Same reasoning
/// import.rs's `merge_import_day_rows` already documents.
async fn encrypt_existing_rows(
    tx: &mut Transaction<'_, Sqlite>,
    cipher: &FieldCipher,
    table: &str,
    key_column: &str,
    value_column: &str,
) -> Result<usize, String> {
    let rows = sqlx::query(&format!("SELECT {key_column}, {value_column} FROM {table}"))
        .fetch_all(&mut **tx)
        .await
        .map_err(|e| format!("couldn't read {table} for encryption: {e}"))?;

    let mut pending: Vec<(String, String)> = Vec::new();
    for row in &rows {
        // reflection's key is INTEGER and the two day-list tables' is TEXT;
        // reading both as a string keeps one code path for all three.
        let key: String = row
            .try_get::<String, _>(key_column)
            .or_else(|_| row.try_get::<i64, _>(key_column).map(|n| n.to_string()))
            .map_err(|e| format!("couldn't read {table}.{key_column}: {e}"))?;
        let value: String = row.try_get(value_column).map_err(|e| format!("couldn't read {table}.{value_column}: {e}"))?;
        if !value.starts_with(MARKER) {
            pending.push((key, value));
        }
    }
    if pending.is_empty() {
        return Ok(0);
    }

    let plaintexts: Vec<String> = pending.iter().map(|(_, v)| v.clone()).collect();
    let ciphertexts = cipher.encrypt_many(&plaintexts).await?;

    for ((key, _), ciphertext) in pending.iter().zip(ciphertexts) {
        sqlx::query(&format!("UPDATE {table} SET {value_column} = ? WHERE {key_column} = ?"))
            .bind(&ciphertext)
            .bind(key)
            .execute(&mut **tx)
            .await
            .map_err(|e| format!("couldn't encrypt a {table} row: {e}"))?;
    }
    Ok(pending.len())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn round_trips_a_value() {
        let cipher = FieldCipher::test_fixed();
        let encrypted = cipher.encrypt("Did yoga").await.unwrap();
        assert!(encrypted.starts_with(MARKER));
        assert!(!encrypted.contains("Did yoga"));
        assert_eq!(cipher.decrypt(&encrypted).await.unwrap(), "Did yoga");
    }

    /// The property the whole nonce discussion rests on: identical plaintext
    /// must not produce identical ciphertext, or an attacker could tell which
    /// slots share an entry (and, with any known plaintext, start unpicking
    /// the rest).
    #[tokio::test]
    async fn same_plaintext_encrypts_differently_every_time() {
        let cipher = FieldCipher::test_fixed();
        let a = cipher.encrypt("Skip").await.unwrap();
        let b = cipher.encrypt("Skip").await.unwrap();
        assert_ne!(a, b, "a fresh nonce must make repeat encryptions of one value unlinkable");
        assert_eq!(cipher.decrypt(&a).await.unwrap(), "Skip");
        assert_eq!(cipher.decrypt(&b).await.unwrap(), "Skip");
    }

    /// Legacy/not-yet-migrated rows must survive a decrypt call untouched --
    /// this is what keeps the app readable between first launch of this
    /// version and the migration finishing.
    #[tokio::test]
    async fn unmarked_plaintext_passes_through_untouched() {
        let cipher = FieldCipher::test_fixed();
        assert_eq!(cipher.decrypt("Went for a walk").await.unwrap(), "Went for a walk");
        assert_eq!(cipher.decrypt("").await.unwrap(), "");
    }

    #[tokio::test]
    async fn empty_and_multiline_values_round_trip() {
        let cipher = FieldCipher::test_fixed();
        for value in ["", "Line one\nLine two", "  leading and trailing  ", "emoji 🌱 and ünïcode"] {
            let encrypted = cipher.encrypt(value).await.unwrap();
            assert_eq!(cipher.decrypt(&encrypted).await.unwrap(), value);
        }
    }

    #[tokio::test]
    async fn a_different_key_cannot_decrypt() {
        let cipher = FieldCipher::test_fixed();
        let encrypted = cipher.encrypt("Did laundry").await.unwrap();
        let other = FieldCipher { key: [9u8; KEY_LEN] };
        assert!(other.decrypt(&encrypted).await.is_err(), "the wrong key must fail loudly, not return garbage");
    }

    #[tokio::test]
    async fn tampered_ciphertext_is_rejected() {
        let cipher = FieldCipher::test_fixed();
        let encrypted = cipher.encrypt("Reviewed the PR").await.unwrap();
        // Flip a character in the base64 body -- AEAD authentication is what
        // should catch this, not a silently wrong plaintext.
        let mut chars: Vec<char> = encrypted.chars().collect();
        let last = chars.len() - 2;
        chars[last] = if chars[last] == 'A' { 'B' } else { 'A' };
        let tampered: String = chars.into_iter().collect();
        assert!(cipher.decrypt(&tampered).await.is_err());
    }

    #[tokio::test]
    async fn batch_round_trips_and_preserves_order() {
        let cipher = FieldCipher::test_fixed();
        let values: Vec<String> = ["first", "second", "third"].iter().map(|s| s.to_string()).collect();
        let encrypted = cipher.encrypt_many(&values).await.unwrap();
        assert_eq!(cipher.decrypt_many(&encrypted).await.unwrap(), values);
    }

    // --- Migration of pre-existing plaintext rows -------------------------

    async fn migration_test_pool() -> sqlx::SqlitePool {
        let pool = sqlx::SqlitePool::connect("sqlite::memory:").await.unwrap();
        sqlx::query(
            "CREATE TABLE reflection (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at TEXT NOT NULL,
                slot_start_at TEXT NOT NULL,
                text TEXT NOT NULL,
                updated_at TEXT
            )",
        )
        .execute(&pool)
        .await
        .unwrap();
        sqlx::query(
            "CREATE TABLE daily_task_list (
                date TEXT PRIMARY KEY,
                content TEXT NOT NULL DEFAULT '',
                updated_at TEXT NOT NULL
            )",
        )
        .execute(&pool)
        .await
        .unwrap();
        sqlx::query(
            // TEXT columns (migration 23), same as production -- see this
            // module's ENCRYPTED_COLUMNS.
            "CREATE TABLE wellness_check (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                slot_start_at TEXT NOT NULL DEFAULT '',
                relaxed_eyes TEXT NOT NULL DEFAULT '1',
                exercise TEXT NOT NULL DEFAULT '1',
                drank_water TEXT NOT NULL DEFAULT '1',
                washroom TEXT NOT NULL DEFAULT '0',
                created_at TEXT NOT NULL
            )",
        )
        .execute(&pool)
        .await
        .unwrap();
        pool
    }

    #[tokio::test]
    async fn migration_encrypts_existing_plaintext_rows() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        sqlx::query(
            "INSERT INTO reflection (id, created_at, slot_start_at, text, updated_at)
             VALUES (1, '2026-01-01T00:00:00.000Z', '2026-01-01T00:00:00.000Z', 'Did yoga', '2026-01-01T00:00:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();

        let mut tx = pool.begin().await.unwrap();
        let count = encrypt_existing_rows(&mut tx, &cipher, "reflection", "id", "text").await.unwrap();
        tx.commit().await.unwrap();
        assert_eq!(count, 1);

        let stored: String =
            sqlx::query_scalar("SELECT text FROM reflection WHERE id = 1").fetch_one(&pool).await.unwrap();
        assert!(stored.starts_with(MARKER), "row should be encrypted in place");
        assert_eq!(cipher.decrypt(&stored).await.unwrap(), "Did yoga", "content must survive the migration verbatim");
    }

    /// The property that makes a crash mid-migration (or a lost/reset
    /// `data_encryption_migrated` flag) harmless rather than destructive:
    /// running the pass again must not encrypt already-encrypted values a
    /// second time, which would leave them undecryptable in one pass.
    #[tokio::test]
    async fn migration_is_idempotent() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        sqlx::query(
            "INSERT INTO reflection (id, created_at, slot_start_at, text, updated_at)
             VALUES (1, '2026-01-01T00:00:00.000Z', '2026-01-01T00:00:00.000Z', 'Did yoga', '2026-01-01T00:00:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();

        for _ in 0..3 {
            let mut tx = pool.begin().await.unwrap();
            encrypt_existing_rows(&mut tx, &cipher, "reflection", "id", "text").await.unwrap();
            tx.commit().await.unwrap();
        }

        // A second pass must report nothing left to do, and one decrypt must
        // still yield the original text (not another layer of ciphertext).
        let mut tx = pool.begin().await.unwrap();
        let count = encrypt_existing_rows(&mut tx, &cipher, "reflection", "id", "text").await.unwrap();
        tx.commit().await.unwrap();
        assert_eq!(count, 0, "an already-encrypted row must not be re-encrypted");

        let stored: String =
            sqlx::query_scalar("SELECT text FROM reflection WHERE id = 1").fetch_one(&pool).await.unwrap();
        assert_eq!(cipher.decrypt(&stored).await.unwrap(), "Did yoga");
    }

    /// Re-encrypting is a storage-format change, not a content edit. Bumping
    /// updated_at would make every paired device re-sync its entire history
    /// on the next P2P sync (that column is the delta cursor -- see CLAUDE.md).
    #[tokio::test]
    async fn migration_leaves_the_sync_cursor_alone() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        sqlx::query(
            "INSERT INTO reflection (id, created_at, slot_start_at, text, updated_at)
             VALUES (1, '2026-01-01T00:00:00.000Z', '2026-01-01T00:00:00.000Z', 'Did yoga', '2026-01-01T09:30:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();
        sqlx::query(
            "INSERT INTO daily_task_list (date, content, updated_at)
             VALUES ('2026-01-01', 'Write report', '2026-01-01T08:00:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();

        let mut tx = pool.begin().await.unwrap();
        encrypt_existing_rows(&mut tx, &cipher, "reflection", "id", "text").await.unwrap();
        encrypt_existing_rows(&mut tx, &cipher, "daily_task_list", "date", "content").await.unwrap();
        tx.commit().await.unwrap();

        let reflection_updated: String =
            sqlx::query_scalar("SELECT updated_at FROM reflection WHERE id = 1").fetch_one(&pool).await.unwrap();
        assert_eq!(reflection_updated, "2026-01-01T09:30:00.000Z");
        let task_updated: String =
            sqlx::query_scalar("SELECT updated_at FROM daily_task_list WHERE date = '2026-01-01'")
                .fetch_one(&pool)
                .await
                .unwrap();
        assert_eq!(task_updated, "2026-01-01T08:00:00.000Z");
    }

    /// `reflection` is keyed by INTEGER and the day-list tables by TEXT --
    /// the migration reads both through one code path, so both need covering.
    #[tokio::test]
    async fn migration_handles_a_text_keyed_table() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        sqlx::query(
            "INSERT INTO daily_task_list (date, content, updated_at)
             VALUES ('2026-01-01', 'Write report\nCall dentist', '2026-01-01T08:00:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();

        let mut tx = pool.begin().await.unwrap();
        let count = encrypt_existing_rows(&mut tx, &cipher, "daily_task_list", "date", "content").await.unwrap();
        tx.commit().await.unwrap();
        assert_eq!(count, 1);

        let stored: String =
            sqlx::query_scalar("SELECT content FROM daily_task_list WHERE date = '2026-01-01'")
                .fetch_one(&pool)
                .await
                .unwrap();
        assert_eq!(cipher.decrypt(&stored).await.unwrap(), "Write report\nCall dentist");
    }

    /// `wellness_check` is the one table with four encrypted columns sharing
    /// a single `id`-keyed row (every other encrypted table has exactly one
    /// value column) -- confirms `ENCRYPTED_COLUMNS`' four separate
    /// (table, "id", column) entries each migrate their own column
    /// independently, without disturbing the other three.
    #[tokio::test]
    async fn migration_handles_wellness_checks_four_columns() {
        let pool = migration_test_pool().await;
        let cipher = FieldCipher::test_fixed();
        sqlx::query(
            "INSERT INTO wellness_check (id, slot_start_at, relaxed_eyes, exercise, drank_water, washroom, created_at)
             VALUES (1, '2026-01-01T00:00:00.000Z', '1', '0', '1', '0', '2026-01-01T00:05:00.000Z')",
        )
        .execute(&pool)
        .await
        .unwrap();

        let mut tx = pool.begin().await.unwrap();
        for column in ["relaxed_eyes", "exercise", "drank_water", "washroom"] {
            encrypt_existing_rows(&mut tx, &cipher, "wellness_check", "id", column).await.unwrap();
        }
        tx.commit().await.unwrap();

        let row = sqlx::query("SELECT relaxed_eyes, exercise, drank_water, washroom FROM wellness_check WHERE id = 1")
            .fetch_one(&pool)
            .await
            .unwrap();
        let expected = [("relaxed_eyes", "1"), ("exercise", "0"), ("drank_water", "1"), ("washroom", "0")];
        for (column, plaintext) in expected {
            let stored: String = row.try_get(column).unwrap();
            assert!(stored.starts_with(MARKER), "{column} should have been stored encrypted, got: {stored}");
            assert_eq!(cipher.decrypt(&stored).await.unwrap(), plaintext, "{column} must survive the migration verbatim");
        }
    }

    /// A batch mixing already-migrated and not-yet-migrated rows is exactly
    /// what a partially migrated database hands `getReflectionsForDate`.
    #[tokio::test]
    async fn batch_decrypt_handles_a_mix_of_encrypted_and_plaintext() {
        let cipher = FieldCipher::test_fixed();
        let encrypted = cipher.encrypt("encrypted row").await.unwrap();
        let mixed = vec![encrypted, "legacy plaintext row".to_string()];
        assert_eq!(
            cipher.decrypt_many(&mixed).await.unwrap(),
            vec!["encrypted row".to_string(), "legacy plaintext row".to_string()]
        );
    }
}
