//! Field-level encryption at rest for the user's own typed content --
//! `reflection.text`, `daily_task_list.content`, and `not_to_do_list.content`
//! (see CLAUDE.md's "Encryption at rest" for the scope and threat model),
//! plus `reflection.created_at`/`updated_at`: those carry no prose, but a
//! plaintext edit timestamp leaks when the user is awake and working, which
//! is exactly the kind of inference the rest of this module exists to
//! prevent.
//!
//! **Why not SQLCipher / whole-database encryption**: tauri-plugin-sql (v2.4.0,
//! read from its own source) opens its pool with a bare `Pool::connect(url)` --
//! there is no hook to issue the `PRAGMA key` SQLCipher requires immediately
//! after connecting, and no way to pass custom connect options. Whole-db
//! encryption would mean forking or vendoring the plugin. Field encryption
//! needs none of that, and costs nothing in query capability here: no code
//! path in this app filters, searches, or sorts on the *value* of any
//! encrypted column (every `WHERE` is on `id`/`slot_start_at`/`date`/`rev`),
//! so an opaque ciphertext blob breaks no query.
//!
//! `created_at`/`updated_at` used to be in that list of things queries run
//! on -- P2P sync compared them to find changed rows. Encrypting them meant
//! that cursor had to move off timestamps entirely, which is what
//! `reflection.rev` and the other synced tables' `rev` columns are for
//! (db.rs's schema, p2p_sync.rs's `build_delta_payload`).
//!
//! **Format**: `enc1:` + base64(`nonce` ‖ `ciphertext` ‖ `tag`), stored in the
//! same existing `TEXT` column. The `enc1:` marker is what makes an
//! unmarked value readable rather than an error: `decrypt` returns anything
//! without it untouched. Nothing in this build writes an unmarked value --
//! the one-time passes that used to encrypt pre-existing plaintext rows are
//! gone, and `db::verify_final_shape` refuses to start against a database
//! that never finished them -- so this is now purely a safety net for a
//! stray row (hand-edited, or restored from somewhere odd) rather than a
//! migration window this app expects to be in.
//!
//! **Nonces are always freshly random, never derived from another column.**
//! That is not a stylistic choice: `updateReflectionText`,
//! `bulkUpsertReflections`, and import.rs's merge-then-`UPDATE` all rewrite
//! `text` for the *same* `id`/`slot_start_at`, so a nonce derived from either
//! would repeat across genuinely different plaintexts under one key -- the
//! failure mode that leaks the XOR of both plaintexts and, for GCM, the
//! authentication key itself. XChaCha20-Poly1305's 192-bit nonce is what
//! makes "just generate a random one every time" safe at any volume without
//! a counter shared between this module's several independent callers
//! (commands.rs for db.ts, import.rs, native_overlay.rs on Android).

// Desktop only: on Android the cipher work happens inside the Keystore via
// the Kotlin bridge, so none of the primitives below are compiled in.
#[cfg(not(target_os = "android"))]
use base64::engine::general_purpose::STANDARD as BASE64;
#[cfg(not(target_os = "android"))]
use base64::Engine as _;
#[cfg(not(target_os = "android"))]
use chacha20poly1305::aead::{Aead, AeadCore, KeyInit, OsRng};
#[cfg(not(target_os = "android"))]
use chacha20poly1305::XChaCha20Poly1305;
#[cfg(not(target_os = "android"))]
use hkdf::Hkdf;
#[cfg(not(target_os = "android"))]
use hmac::{Hmac, Mac};
#[cfg(not(target_os = "android"))]
use sha2::Sha256;
use tauri::AppHandle;

/// Marks a stored value as ciphertext this module produced. Anything without
/// it is treated as plaintext and passed through untouched.
const MARKER: &str = "enc1:";

/// XChaCha20-Poly1305's nonce width. The whole reason this cipher was picked
/// over AES-256-GCM's 96 bits -- see the module doc comment. (Android's
/// Keystore path uses AES-GCM with its own 12-byte IV instead, generated by
/// the platform -- see NativeBridgePlugin.kt.)
#[cfg(not(target_os = "android"))]
const NONCE_LEN: usize = 24;

#[cfg(not(target_os = "android"))]
pub(crate) const KEY_LEN: usize = 32;

/// HKDF `info` label for the HMAC subkey that backs
/// `screen_time_session.app_id_hash` (see `FieldCipher::blind_index_many`).
/// Never the raw AEAD key itself -- reusing one raw key for two different
/// cryptographic primitives (AEAD encryption and a MAC) is a key-separation
/// anti-pattern this label exists to avoid. Android has no equivalent
/// derivation: its Keystore key is non-exportable, so it uses a second,
/// independently generated Keystore HMAC key instead (see
/// android_bridge.rs's `hmac_fields` / `NativeBridgePlugin.kt`'s
/// `HMAC_KEY_ALIAS`) rather than deriving anything from the AEAD key.
#[cfg(not(target_os = "android"))]
const BLIND_INDEX_HKDF_INFO: &[u8] = b"reflectodoro/screen_time/app_id_hash/v1";

// --- Cipher handle ---------------------------------------------------------

/// Resolved once per operation (or once per import/sync batch) and reused for
/// every field in it, rather than re-fetching the key per row: on Linux that
/// fetch is a D-Bus round trip, and on Android every call is a JNI hop into
/// the Keystore.
///
/// The platform split lives inside this one type so every caller
/// (commands.rs, import.rs, p2p_sync.rs, native_overlay.rs) is written once
/// against the same API: on desktop it carries the raw key and does the
/// crypto here in Rust; on Android it carries the `AppHandle` and delegates
/// to the Keystore through the Kotlin bridge, because an Android Keystore key
/// is non-exportable by design -- Rust never sees key material there.
#[derive(Clone)]
pub struct FieldCipher {
    #[cfg(not(target_os = "android"))]
    key: [u8; KEY_LEN],
    #[cfg(target_os = "android")]
    app: AppHandle,
}

impl FieldCipher {
    #[cfg(not(target_os = "android"))]
    pub async fn resolve(app: &AppHandle) -> Result<Self, String> {
        // Where the key lives (OS vault or password-protected file) and
        // whether it's unlocked is key_store.rs's business; a locked key
        // surfaces here as its `KEY_LOCKED:` error.
        Ok(Self { key: crate::key_store::key(app).await? })
    }

    #[cfg(target_os = "android")]
    pub async fn resolve(app: &AppHandle) -> Result<Self, String> {
        Ok(Self { app: app.clone() })
    }

    /// Encrypts one value. Always produces a fresh nonce, so calling this
    /// twice on identical input yields two unrelated ciphertexts.
    pub async fn encrypt(&self, plaintext: &str) -> Result<String, String> {
        Ok(self.encrypt_many(std::slice::from_ref(&plaintext.to_string())).await?.remove(0))
    }

    /// Returns `stored` unchanged when it carries no `enc1:` marker.
    /// Deliberately not an error: such a row is genuinely plaintext and
    /// genuinely readable, and erroring would turn a single odd row into an
    /// unusable page. No normal path produces one anymore (see the module
    /// comment), so this is a safety net, not an expected case.
    pub async fn decrypt(&self, stored: &str) -> Result<String, String> {
        if !stored.starts_with(MARKER) {
            return Ok(stored.to_string());
        }
        Ok(self.decrypt_many(std::slice::from_ref(&stored.to_string())).await?.remove(0))
    }

    #[cfg(not(target_os = "android"))]
    pub async fn encrypt_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        values.iter().map(|v| encrypt_with_key(&self.key, v)).collect()
    }

    #[cfg(not(target_os = "android"))]
    pub async fn decrypt_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        values.iter().map(|v| decrypt_with_key(&self.key, v)).collect()
    }

    /// One bridge call for the whole batch rather than one per value -- every
    /// call here is a JNI hop plus a Keystore `Cipher` init.
    #[cfg(target_os = "android")]
    pub async fn encrypt_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        crate::android_bridge::encrypt_fields(&self.app, values)
    }

    #[cfg(target_os = "android")]
    pub async fn decrypt_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        // Unmarked values never reach Kotlin: they're legacy plaintext and
        // would fail base64/AEAD decoding there. Same passthrough rule as
        // `decrypt`, applied per element so a mixed batch (part migrated,
        // part not) still works.
        let marked: Vec<String> = values.iter().filter(|v| v.starts_with(MARKER)).cloned().collect();
        if marked.is_empty() {
            return Ok(values.to_vec());
        }
        let mut decrypted = crate::android_bridge::decrypt_fields(&self.app, &marked)?.into_iter();
        values
            .iter()
            .map(|v| {
                if v.starts_with(MARKER) {
                    decrypted.next().ok_or_else(|| "android bridge returned too few values".to_string())
                } else {
                    Ok(v.clone())
                }
            })
            .collect()
    }

    /// Deterministic "blind index" for `screen_time_session.app_id` (see
    /// CLAUDE.md's "Encryption at rest"): the same input always produces the
    /// same output under one device's key, which is what lets
    /// `getScreenTimeForDate`'s `GROUP BY` and `import.rs`'s duplicate check
    /// keep working in SQL once `app_id` itself is random-nonce ciphertext
    /// (and therefore never equal to itself across two encryptions). Never
    /// used to recover the plaintext -- HMAC isn't reversible -- only to
    /// tell "these two rows are the same app" apart from "different apps".
    #[cfg(not(target_os = "android"))]
    pub async fn blind_index_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        let hk = Hkdf::<Sha256>::new(None, &self.key);
        let mut subkey = [0u8; 32];
        hk.expand(BLIND_INDEX_HKDF_INFO, &mut subkey).map_err(|e| format!("HKDF expand failed: {e}"))?;
        values
            .iter()
            .map(|v| {
                // Fully qualified: `KeyInit` (already in scope for the AEAD
                // cipher above) and `hmac::Mac` both define
                // `new_from_slice`, which is ambiguous without this.
                let mut mac = <Hmac<Sha256> as Mac>::new_from_slice(&subkey)
                    .map_err(|e| format!("HMAC init failed: {e}"))?;
                mac.update(v.as_bytes());
                Ok(BASE64.encode(mac.finalize().into_bytes()))
            })
            .collect()
    }

    /// Android has no raw key to derive from (see `BLIND_INDEX_HKDF_INFO`'s
    /// doc comment), so this runs against a second, independently generated
    /// Keystore HMAC key instead, entirely inside Kotlin.
    #[cfg(target_os = "android")]
    pub async fn blind_index_many(&self, values: &[String]) -> Result<Vec<String>, String> {
        crate::android_bridge::hmac_fields(&self.app, values)
    }

    /// Fixed-key cipher for tests (import.rs's DB-backed tests in
    /// particular), which have no `AppHandle` and must not touch the real
    /// OS credential store.
    #[cfg(test)]
    pub fn test_fixed() -> Self {
        Self { key: [7u8; KEY_LEN] }
    }
}

// --- Cipher primitives (desktop) -------------------------------------------

#[cfg(not(target_os = "android"))]
fn encrypt_with_key(key: &[u8; KEY_LEN], plaintext: &str) -> Result<String, String> {
    let cipher = XChaCha20Poly1305::new(key.into());
    let nonce = XChaCha20Poly1305::generate_nonce(&mut OsRng);
    let ciphertext = cipher
        .encrypt(&nonce, plaintext.as_bytes())
        .map_err(|e| format!("encryption failed: {e}"))?;
    let mut blob = Vec::with_capacity(NONCE_LEN + ciphertext.len());
    blob.extend_from_slice(&nonce);
    blob.extend_from_slice(&ciphertext);
    Ok(format!("{MARKER}{}", BASE64.encode(blob)))
}

#[cfg(not(target_os = "android"))]
pub(crate) fn decrypt_with_key(key: &[u8; KEY_LEN], stored: &str) -> Result<String, String> {
    let Some(encoded) = stored.strip_prefix(MARKER) else {
        return Ok(stored.to_string());
    };
    let blob = BASE64.decode(encoded).map_err(|e| format!("ciphertext is not valid base64: {e}"))?;
    if blob.len() <= NONCE_LEN {
        return Err("ciphertext is too short to contain a nonce".to_string());
    }
    let (nonce, ciphertext) = blob.split_at(NONCE_LEN);
    let cipher = XChaCha20Poly1305::new(key.into());
    // A failure here is authentication failing, which in practice means the
    // wrong key -- most plausibly a credential store that lost or rotated
    // this app's entry. Surfaced as an error rather than silently swallowed:
    // pretending a row is empty would look exactly like "the user wrote
    // nothing", and the Entries page would quietly render a blank day.
    let plaintext = cipher
        .decrypt(nonce.into(), ciphertext)
        .map_err(|_| "decryption failed (wrong key, or the stored value was modified)".to_string())?;
    String::from_utf8(plaintext).map_err(|e| format!("decrypted value is not valid UTF-8: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn round_trips_a_value() {
        let cipher = FieldCipher::test_fixed();
        let encrypted = cipher.encrypt("Did yoga").await.unwrap();
        assert!(encrypted.starts_with(MARKER));
        assert!(!encrypted.contains("Did yoga"));
        assert_eq!(cipher.decrypt(&encrypted).await.unwrap(), "Did yoga");
    }

    /// The property the whole nonce discussion rests on: identical plaintext
    /// must not produce identical ciphertext, or an attacker could tell which
    /// slots share an entry (and, with any known plaintext, start unpicking
    /// the rest).
    #[tokio::test]
    async fn same_plaintext_encrypts_differently_every_time() {
        let cipher = FieldCipher::test_fixed();
        let a = cipher.encrypt("Skip").await.unwrap();
        let b = cipher.encrypt("Skip").await.unwrap();
        assert_ne!(a, b, "a fresh nonce must make repeat encryptions of one value unlinkable");
        assert_eq!(cipher.decrypt(&a).await.unwrap(), "Skip");
        assert_eq!(cipher.decrypt(&b).await.unwrap(), "Skip");
    }

    /// Legacy/not-yet-migrated rows must survive a decrypt call untouched --
    /// this is what keeps the app readable between first launch of this
    /// version and the migration finishing.
    #[tokio::test]
    async fn unmarked_plaintext_passes_through_untouched() {
        let cipher = FieldCipher::test_fixed();
        assert_eq!(cipher.decrypt("Went for a walk").await.unwrap(), "Went for a walk");
        assert_eq!(cipher.decrypt("").await.unwrap(), "");
    }

    #[tokio::test]
    async fn empty_and_multiline_values_round_trip() {
        let cipher = FieldCipher::test_fixed();
        for value in ["", "Line one\nLine two", "  leading and trailing  ", "emoji 🌱 and ünïcode"] {
            let encrypted = cipher.encrypt(value).await.unwrap();
            assert_eq!(cipher.decrypt(&encrypted).await.unwrap(), value);
        }
    }

    #[tokio::test]
    async fn a_different_key_cannot_decrypt() {
        let cipher = FieldCipher::test_fixed();
        let encrypted = cipher.encrypt("Did laundry").await.unwrap();
        let other = FieldCipher { key: [9u8; KEY_LEN] };
        assert!(other.decrypt(&encrypted).await.is_err(), "the wrong key must fail loudly, not return garbage");
    }

    #[tokio::test]
    async fn tampered_ciphertext_is_rejected() {
        let cipher = FieldCipher::test_fixed();
        let encrypted = cipher.encrypt("Reviewed the PR").await.unwrap();
        // Flip a character in the base64 body -- AEAD authentication is what
        // should catch this, not a silently wrong plaintext.
        let mut chars: Vec<char> = encrypted.chars().collect();
        let last = chars.len() - 2;
        chars[last] = if chars[last] == 'A' { 'B' } else { 'A' };
        let tampered: String = chars.into_iter().collect();
        assert!(cipher.decrypt(&tampered).await.is_err());
    }

    #[tokio::test]
    async fn batch_round_trips_and_preserves_order() {
        let cipher = FieldCipher::test_fixed();
        let values: Vec<String> = ["first", "second", "third"].iter().map(|s| s.to_string()).collect();
        let encrypted = cipher.encrypt_many(&values).await.unwrap();
        assert_eq!(cipher.decrypt_many(&encrypted).await.unwrap(), values);
    }

    // --- Blind index (screen_time_session.app_id_hash) ---------------------

    /// The property `getScreenTimeForDate`'s `GROUP BY` and `import.rs`'s
    /// duplicate check both rest on: the same plaintext under one key always
    /// produces the same hash, unlike `encrypt` (which never repeats).
    #[tokio::test]
    async fn blind_index_is_deterministic() {
        let cipher = FieldCipher::test_fixed();
        let a = cipher.blind_index_many(&["chrome.exe".to_string()]).await.unwrap();
        let b = cipher.blind_index_many(&["chrome.exe".to_string()]).await.unwrap();
        assert_eq!(a, b);
    }

    #[tokio::test]
    async fn blind_index_differs_for_different_values() {
        let cipher = FieldCipher::test_fixed();
        let hashes = cipher.blind_index_many(&["chrome.exe".to_string(), "notepad.exe".to_string()]).await.unwrap();
        assert_ne!(hashes[0], hashes[1]);
    }

    /// A device's hash values must not match another device's for the same
    /// app name -- this is what makes the "won't link across users" property
    /// hold without any coordination between devices.
    #[tokio::test]
    async fn blind_index_differs_across_keys() {
        let a = FieldCipher::test_fixed();
        let b = FieldCipher { key: [9u8; KEY_LEN] };
        let hash_a = a.blind_index_many(&["chrome.exe".to_string()]).await.unwrap();
        let hash_b = b.blind_index_many(&["chrome.exe".to_string()]).await.unwrap();
        assert_ne!(hash_a, hash_b);
    }

    /// Proves the HMAC subkey is actually derived via HKDF rather than the
    /// raw AEAD key being reused directly as the MAC key -- the key-
    /// separation property the whole `BLIND_INDEX_HKDF_INFO` label exists
    /// for.
    #[tokio::test]
    async fn blind_index_does_not_use_the_raw_aead_key_directly() {
        let cipher = FieldCipher::test_fixed();
        let hash = cipher.blind_index_many(&["chrome.exe".to_string()]).await.unwrap().remove(0);

        let mut raw_key_mac = <Hmac<Sha256> as Mac>::new_from_slice(&cipher.key).unwrap();
        raw_key_mac.update(b"chrome.exe");
        let raw_key_hash = BASE64.encode(raw_key_mac.finalize().into_bytes());

        assert_ne!(hash, raw_key_hash);
    }

    /// The `enc1:` passthrough, batched: an unmarked value comes back as-is
    /// rather than failing the whole batch. Nothing in this build writes an
    /// unmarked value anymore, but this is the safety net that keeps a stray
    /// one (a hand-edited row, a database restored from somewhere odd)
    /// readable instead of turning it into a hard decrypt error.
    #[tokio::test]
    async fn batch_decrypt_handles_a_mix_of_encrypted_and_plaintext() {
        let cipher = FieldCipher::test_fixed();
        let encrypted = cipher.encrypt("encrypted row").await.unwrap();
        let mixed = vec![encrypted, "legacy plaintext row".to_string()];
        assert_eq!(
            cipher.decrypt_many(&mixed).await.unwrap(),
            vec!["encrypted row".to_string(), "legacy plaintext row".to_string()]
        );
    }

}
